### ISSUE TITLE
MathJax not found on the webpages

### ISSUE THREAD

**Issue by Naereen** [boazbk/tcs#1]
Hi,
First, whoo :clap: bravo for this work, it might be a work in progress but it is already quite complete and impressive. Well done! Keep doing that!

Second, I tried to access the website with different browsers, and apparently MathJax is not loaded correctly.
I see that you are using a cloudfront CDN, but [even if cdn.mathjax.org](https://www.mathjax.org/cdn-shutting-down/) is dead now, the official suggested CDN is `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js`.

Also, I don't know how do you compile the PDF book and the website, and maybe it could be useful to also open-source the build script, if that doesn't bother you?
Ideally, for such projects, I think anyone could download the zip archive, rebuild the PDF with something as simple as "make pdf", et voilà. For instance, we have tried that for [@LaurentClaessens's mazhe](https://github.com/LaurentClaessens/mazhe/).

Thanks in advance.

**Comment by boazbk** [comment]
Thank you!!
I think it's fixed now - some overeager optimization on the part of my host. 

I'm using scripts written by David Steurer for sumofsquares.org Right now they are in a pretty unstable situation but I think eventually he plans to publish them on a public repository as well.

**Comment by Naereen** [comment]
OK, thanks.
