### ISSUE TITLE
inconsistency description of "Restrictions on indices" in NAND

### ISSUE THREAD

**Issue by cyyever** [boazbk/tcs#11]
lec 03 says 
> 
As mentioned in the appendix, we require that all output variables are assigned a value, and that the largest index used in an 𝐿 line NAND program is smaller than 𝐿, and so all functions in 𝑆𝐼𝑍𝐸(𝐿) have at most 𝐿 inputs and 𝐿 outputs.
> 

but  appendix says 
>
 If the variable identifiers are indexed, the index can never be larger than the number of lines in the program.
> 

so in order to make this single line program "y_0 := x_0 NAND x_1" valid

 "the largest index used in an 𝐿 line NAND program is smaller than 𝐿"
should be changed to
"the largest index used in an 𝐿 line NAND program is smaller than  or equal to  𝐿"

and for the same reason ,in lec05 we should change 
> 
Of course this limitation is inherent for the NAND programming language where an 𝑁-line program can never compute a function with more than 𝑁 inputs. 
> 
to
> 
with more than 2*𝑁 inputs. 
>

**Comment by cyyever** [comment]
may be there are other places that need change too

**Comment by boazbk** [comment]
Thanks. Actually I think it's cleaner to change the appendix, so the requirement would be that the  number of variables cannot be more than the number of lines.
