### ISSUE TITLE
Wrong binary representation in "Representing (potentially negative) integers"?

### ISSUE THREAD

**Issue by CraigStuntz** [boazbk/tcs#111]
In chapter 2, "Representing (potentially negative) integers," it says:

> For example, recall that we represent 4 as (0,1) and 35 as (1,1,0,0,0,1)

I think 4 should be (0,0,1) here.

**Comment by boazbk** [comment]
You're right - thanks!

**Comment by CraigStuntz** [comment]
I think the revised commit is still not right. Now it says:

> For example, recall that we represent $4$ as $(0,0,1)$ and  $35$ as $(1,1,0,0,0,1)$, but the concatenation  $(0,1,1,1,0,0,0,1)$

But it should say:

_For example, recall that we represent $4$ as $(0,0,1)$ and  $35$ as $(1,1,0,0,0,1)$, but the concatenation  $(0,0,1,1,1,0,0,0,1)$_

**Comment by boazbk** [comment]
test
