### ISSUE TITLE
Possible typo in math background notes 

### ISSUE THREAD

**Issue by Shamazo** [boazbk/tcs#13]
In the clean proof for "Every connected undirected graph of 𝑛n vertices has at least 𝑛−1n−1 edges", I beleive there is a typo in this paragraph:

![image](https://user-images.githubusercontent.com/5744542/30036062-d9457be0-917d-11e7-962b-0adc0d284b35.png)

On the second line should this read a graph of k edges? Because otherwise it would be self evident that any vertex in a graph with k vertices would have fewer than k + 1 connected vertices.  

Note I am reading from the website so this may be different from what is in the repository.

- Hamish Nicholson

**Comment by boazbk** [comment]
Thank you!
