### ISSUE TITLE
Possible typo in Lecture 3

### ISSUE THREAD

**Issue by a11i5on** [boazbk/tcs#14]
For Theorem 3.5 (p. 107), it mentions a function "H". Would this possibly be referring to a different function, as I don't see H being defined anywhere prior? 
<img width="313" alt="lec3" src="https://user-images.githubusercontent.com/21965538/30110239-641281a0-92d7-11e7-8c39-67baabbd4612.PNG">

**Comment by boazbk** [comment]
Yes it is a typo -thanks!

**Comment by boazbk** [comment]
If you tell me your name I will add you to the acknowledgements.

**Comment by a11i5on** [comment]
Hello,

My name is Allison Lee-- thank you for the clarification!
