### ISSUE TITLE
Contents - Formatting issue

### ISSUE THREAD

**Issue by JoshuaZelinsky** [boazbk/tcs#141]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

**List of bugs/typos**

1. In some of the content section lists, the first letter of the section title runs into the section number. In particular, 12.10 Acknowledgements has this issue, appearing as "12.10Acknowledgements" . Same issue for 15.10,15.11,15.12, 19.10, 20.11 through 20.15, and 22.10.

Joshua Zelinsky

**Comment by boazbk** [comment]
Thanks! I fixed this now and should post the fixed version soon.
FYI the code to fix this was:

\usepackage{tocloft}

\renewcommand\cftsecnumwidth{3em}
\renewcommand\cftsubsecnumwidth{3.5em}
