### ISSUE TITLE
Introduction - wording of aside about astronomy

### ISSUE THREAD

**Issue by JoshuaZelinsky** [boazbk/tcs#142]
In the introduction you write that telescopes are "our only means of connecting theoretical speculations with actual experimental observations."  Suggest replacing "only" with "primary" since we have naked eye observations,  neutrino observatories (although those are sometimes called "neutrino telescopes"), and cosmic ray detection systems. 

Josh Zelinsky

**Comment by boazbk** [comment]
Good point though I do want to think of "telescopes" (as well as computers) in a fairly generic sense, and so "primary" looks a little weak for this metaphor.  So I think I will rephrase it in a way that doesn't explicitly say "only" but sort of still suggests it.. how about 


"This quote is typically read as disparaging the importance of actual physical computers in Computer Science, but note that telescopes are absolutely essential to astronomy as they provide us with the means to connect  theoretical speculations with actual experimental observations."

**Comment by JoshuaZelinsky** [comment]
That looks good to me.

**Comment by boazbk** [comment]
Thanks!

**Comment by boazbk** [comment]
While I'm at it, I think "predictions" is better than "speculations"
