### ISSUE TITLE
Typo/inconsistencies in the chapter dependencies

### ISSUE THREAD

**Issue by SOberhoff** [boazbk/tcs#145]
The chapter dependencies mention "staightline programs" which should probably be st**r**aightline programs.

Also complexity classes are once written in bold face under Part III, and in blackboard bold under Part IV.

By the way, my full name is Sebastian Oberhoff. Though I'm worried about the length of the preface if you're going to list everybody that catches a single error.

**Comment by boazbk** [comment]
Thank you! Will be fixed - and I'm not worried - these are good problems to have - I'd much rather have a long preface than a book full of errors :)
