### ISSUE TITLE
(Minor) Ambiguity in 0.1

### ISSUE THREAD

**Issue by rnrand** [boazbk/tcs#148]
Footnote 7:

> The last term is not exactly a single
digit multiplication as ֓ + ֓ and ֔ + ֔
are numbers between 0 and 18 and
not between 0 and 9. As we’ll see, it
turns out that does not make much of
a difference, since when we use the
algorithm recursively, this term will
have essentially half the number of
digits as the original input.

I found this confusing, as it is the *middle term* in equation 2 (right next to the footnote). I would maintain the order of the terms in both places and say "middle term".

**Comment by boazbk** [comment]
Good point. Changed the footnote explicitly to say "The  term $(\overline{x}+\underline{x})(\overline{y}+\underline{y})$..."
