### ISSUE TITLE
typo in lec 04 

### ISSUE THREAD

**Issue by cyyever** [boazbk/tcs#15]
change
> By rounding up $st$ to the nearest power of $2$ (which at most doubles its size), we can assume the array avars is of length $2^k$ for $k=\lceil st \rceil$. 

> 

to

> 
By rounding up $st$ to the nearest power of $2$ (which at most doubles its size), we can assume the array avars is of length $2^k$ for $k=log (\lceil st \rceil$). 
> 

add log function to st.

**Comment by boazbk** [comment]
Thanks!
