### ISSUE TITLE
Quantum Computing

### ISSUE THREAD

**Issue by ardarico** [boazbk/tcs#150]
**List of bugs/typos**

1. In section "Quantum Amplitudes", when discussing outcome probabilities, there is a reference to some note 2, but the text of the note is not displayed.

2. In section "Bell's Inequality", in the proof of Bell's inequality Theorem, ".. the theorem can **be be** violated **if if**..". Also, it is not clear what the asterisk between parentheses means in the equation

f(x) XOR f(y) = x AND y (*)

3. In section "Quantum Weirdness", in the box "More on quantum" the name Vazirani is mispelled (Variani). 

4. In section "Quantum Weirdness", the name Deutsch is mispelled (Detusch). 

5. In Note 7, "the TLS protocol (which based.." --> "the TLS protocol (which is based.."

6. In section "Quantum Systems", in the definition of the matrix corresponding to the Hadamard operation, the +1 may be replaced by 1, as usual. 

7. In section "Quantum Systems", in subsection "Recap", in the last two paragraphs, state "v" is written as a scalar, rather than |v>. 

8. In section "Quantum Systems", in subsection "Analysis of Bell's Inequality (optional)", the first statement repeats "show" and "showing". 

9. In section "Quantum Systems", in subsection "Analysis of Bell's Inequality (optional)", state "s" is written as a scalar, rather than |s>. There, "the first qubit of s" ("the second qubit of s") should be replaced by "the first qubit" ("the second qubit") - the reason is that usually one says "the state of a qubit", rather than "the qubit of a state".

10. In section "Quantum Computation", in subsection "Quantum circuits and QNAND":
"Therefore, we cannot use the same bit as input for two different gates." 
--> "Therefore, we cannot use the same qubit as input for two different gates."

11. In section "Quantum Computation", in subsection "Quantum circuits and QNAND":
"We say that the circuit computes f is the probability.."
--> "We say that the circuit computes f if the probability.."

12. In section "Quantum Computation", in subsection "Quantum circuits and QNAND", in the Def. of Quantum Circuit, the {UNAND,HAD} basis should be {U_{NAND},HAD}

13. In section "Quantum Computation", in subsection "Quantum circuits and QNAND", in the Def. of BQP/poly: 
"is the restriction of to inputs"
--> "is the restriction of F to inputs"

14. In section "Shor's Algorithm": 
"Bell's inequality is powerful demonstration.."
--> "Bell's inequality is a powerful demonstration.."
"will sketch some of the ideas"
--> "we will sketch some of the ideas"

That's all for now! I like this chapter very much. I will open another issue to provide suggestions for clarifying a few parts.

**Comment by boazbk** [comment]
Thanks - fixed! (Not yet compiled though.)

In this chapter I use the ket notation only for the standard basis elements.

Added more details to the proof of the strategy of Bell's Inequality as well.
