### ISSUE TITLE
Preface

### ISSUE THREAD

**Issue by marikaswanberg** [boazbk/tcs#151]
**Chapter name**: Preface

**List of bugs/typos**
Page 19, section 0.1 “To the student”
1. On the second bullet point, the sentence “Try to think of the motivation behind the definition, and there other natural ways to formalize the same concept” should be corrected to “Try to think of the motivation behind the definition and other natural ways to formalize the same concept” (omit the “there” and the comma).
2. On the third bullet point, the sentence “At any point in the text, try to think what are the natural questions that arise, and see whether or not they are answered in the following” is kind of awkward. My suggested revision is “Actively notice which questions arise as you read the text, and whether the text answers your questions.”, but obviously there are lots of other possible revisions that you may like better.
Page 21, section 0.2
3.  In the second bullet point, “...transforming a NAND++ program to an instance of CIRCUIT SAT ### **can (and is) be done** in a handful of lines…” should be revised to “...transforming a NAND++ program to an instance of CIRCUIT SAT **can be (and is) done** in a handful of lines…”
4. “Reducing the time dedicated to automata and context free languages allows to spend more time on topics…” Should be “Reducing the time dedicated to automata and context free languages allows for more time to spend on topics…” Or another way is to say “allows me to spend more time on topics”
“Section 0.4 contains a ‘roadmap’ for this book, with description of the different chapters.” Instead, maybe “Section 0.4 contains a ‘roadmap’ for this book, with descriptions of each chapter.”

**Comment by boazbk** [comment]
Thank you! Just made the changes (not compiled yet but pushed to the repository)
