### ISSUE TITLE
Chapter 1:Mathematical Background

### ISSUE THREAD

**Issue by marikaswanberg** [boazbk/tcs#154]
**Chapter name**: Mathematical Background.

**List of bugs/typos**
1.1 A Mathematician’s apology

- After all, there is no empirical experiment that will prove the **non existence** of an algorithm. (Should be **nonexistence**)
1.3 Reading Mathematical Texts
- “You should not expect it to be clear in a first reading, but you should not despair immediately, but rather engage with the text, trying to figure out both the high level intentions as well as the underlying details.” -This sentence needs to be broken up into two or more sentences because there are many clauses here. 
- “Luckily, mathematicians **have a greater discipline of** introducing definitions in linear order, and making sure that every concept is defined only in terms of concepts that have been previously defined.” I’m not sure what the “having discipline of” part of the sentence is trying to say. Greater than who?
-“As you read through the rest of this chapter and this text, try to **ask yourself the questions 1-3 above** every time that you encounter a new definition.” The bolded part should just be “ask yourself questions 1-3 above”
1.3.1 Example: Defining a one-to-one function
- Definition 1.3. This is completely a matter of personal preference, but I’m much more familiar with the “contrapositive” version of the definition of injectivity you’ve given, and it seems more intuitive to me. I.e. f(x) = f(y) implies x = y. If you want to keep it the way you have it, I think you may want to state it like “for every x,x’ in S where x != x’...” because it’s not quite clear that x and x’ are in S (to someone seeing this definition for the first time, that is).
- “Make sure you understand **how are the identifiers quantified.**” Should be “Make sure you understand **how the identifiers are quantified**”.
- This is just a small technical thing, but you wrote “For example, Definition 1.3 says that a one to one function is a function where every input is mapped to a unique output.” But I think you may want to insert that “every **unique** input is mapped to a unique output. 
Figure 1.2: A snippet from the methods of the alpha go paper
- It looks like this image has somewhat poor resolution. If there is a better resolution photo of the same thing, you may want to use that. The same applies to Figure 1.3, the Zerocash paper.
1.4.1 Sets
- You wrote “The cardinality of a finite set,denoted by | |, is the number of **distinct elements** it contains.” This is a little confusing, because you already stated that all elements of a set are distinct. I would omit the “distinct” because it’s implied by the previous statement.
- The formatting on the word “EVEN” puts a space in between the V and E so it looks like “EV EN”
- There’s a missing symbol, I assume a slash: “The set difference of S and T , denoted by **S T**”  (and in some texts also by S − T) 
- Typo: “Just like sets, we can also think of **an infinite analogs of tuples**, such as the ordered collection” (should be “analog” not “analogs”)
- Concatenation: “The concatenation of two strings x ∈ Σ^n and y ∈ Σ^m is the (n+m)-length string xy obtained by writing y after x. That is,(xy)_i equals x_i if  i< n and equals y_{i-n}  if n ≤ i <n +m.” This took me a couple of minutes to parse, and I’m used to working with regular expressions. I think this would be clearer if, rather than using subscript notation like (xy)_i, you said “the ith digit of our string xy is...” or something. I also don’t know if this technical definition of concatenation is totally necessary, and it may just confuse people like it did to me :P . You might consider putting a simple example of concatenation instead, like if x = “cat” and y=”dog” then xy = “catdog”. (Also, you write this technical definition of concatenation in section 1.4.3 Special Sets, so you may not need it in both of these places, but that choice is up to you).
1.4.4 Functions
- This is a small technical point, but your definition of a function, that it “associates with every element x in S an element F(x) in T” is missing the requirement that functions map every x in S to a unique element F(x) in T (ie F can’t map x to two things). 
- Also, the definition “the set T is known as the range or co-domain of F” isn’t quite correct because the range (also known as the image of F) is not T. It’s correct that T is the codomain, but T is not the range of F unless F is surjective. Also, codomain doesn’t have a hyphen. 
- You wrote “Then the function F defined by the input output behavior as in the table below, is the same as defining F(x) = (x mod 2). I think the first parenthesis is misplaced because standard notation (at least what I’ve seen in my textbooks) is F(x) = x (mod 2).
- In your definition of surjection: “If F satisfies that for every y in T there is some x such that F(x) = y” you need to state that x is in S. 
- “In particular, the cardinality of a set S **is defined n** if there is a bijection from S”. This should probably be reworded. One suggestion: “A set S has cardinality n if there is a bijection from S….”
- Partial functions: “This is a generalization of the notion of **a function to consider also F that is** not necessarily defined on every element of S.” This wording is a little confusing and not grammatically correct.
- I think I found a problem with one of your basic facts about functions. The one that says if F : S -> T is one to one, then there exists an onto function G: T->S such that G(F(s)) = s for every s in S. You either need the requirement that S and T are nonempty (which you use in your proof), or that G is allowed to be only a partial function. 
- Figure 1.4 (Examples of functions that are injective, surjective, and neither). You write that “The onto condition corresponds to requiring that every vertex in the **range of the function** has in-degree at least one.” This is not quite right, since the range (or image) corresponds to the points in the codomain that F actually “touches”. So, replace “range” with “codomain” and you’re good. (In fact, saying a function F is surjective is equivalent to saying the range/image of F = the codomain of F.) The sentence about injectivity is the correct usage of range.
1.4.5 Graphs
- Typos: “They are used to model a variety of data types including social networks, road networks, deep **nueral** nets, gene interactions, correlations between observations, and a great many more.” (Should be neural nets) Also, you should probably have a comma after “types” and a colon before the list: “They are used to model a variety of data types, including: social networks, road networks, deep **neural** nets, gene interactions, correlations between observations, and a great many more.”
- Typo: “We define **(the)** degree of u to be the number of neighbors u has” 
1.4.6 Logic operators and quantifiers
- Typo: You start off this section with the sentence: “If P and Q are some statements that can be true or false, then P AND Q (**denoted as** P^Q)..... and P OR Q (**denoted as**…)” The “as” shouldn’t be there. You can just say “denoted P^Q” in both places, and also the next sentence
1.4.8 Parsing formulas: bound and free variables
- The beginning of first sentence: “In mathematics as in code, we often….” is a little awkward. I understand the meaning, but it’s just not quite correct. I think if you added a comma, this would be correct: “In mathematics, as in code, we often…” 
- Typo: “For example, in the following statement n is free but **a,b** are bound by the exists quantifier” I think you need to say “a **and** b”
1.4.9 Asymptotics and big-Oh notation
- A technical point in your definition of big O. You write that the constant “a” is in the natural numbers, but you’ve defined N to contain 0. Now that I think of it, I’m not sure why all of the other definitions require that the constant be positive, but your allowance of a zero constant is at least inconsistent with definitions I’ve seen. I’m not sure if it’s technically wrong, though.

I'm not done reading the chapter, but I figured I could post these for now, and I'll add on to this as I finish the chapter.

**Comment by boazbk** [comment]
Thanks so much!!

Apparently the definition of range changed since my school days... I remembered range as being what's now called as codomain (a term I only heard about recently) but will just avoid it and use codomain or image.. (hopefully will remember to do so..)

I'd rather not talk about functions with empty domain or codomain so just added this qualifier.

Are you sure about the "denoted as"? it reads to me better, but maybe that's just because I'm a nonnative speaker.

I think it doesn't matter about a=0, since I defined the functions to have a positive output, and so you cannot have them equal zero.

**Comment by marikaswanberg** [comment]
I'm not totally sure about the "denoted as".... To me "denoted" sounds better but, I have two native languages so sometimes I also don't hear which one is correct, or I mix up the two languages.  
I'm glad the feedback was helpful... I know I can be pedantic sometimes.
