### ISSUE TITLE
[Mathematical Background] Incorrect ref number in image

### ISSUE THREAD

**Issue by SmedbergM** [boazbk/tcs#157]
**Mathematical Background**: 

**List of bugs/typos**

1. `figure/onetoonedef.png` is out of date. The image shows the Definition number as 0.3, when it is (currently) 1.3. (formula ref `onttoonedef`)

**Comment by boazbk** [comment]
I know, I changed the numbering after I did this image. I think will leave it untouched for a while and will only fix it once I am sure the numbering will not change again.

**Comment by boazbk** [comment]
Will be fixed in new version
