### ISSUE TITLE
typo in section 2.1.5, page 78

### ISSUE THREAD

**Issue by JasonMa2016** [boazbk/tcs#16]
The side note says "that there is way to "count" all the reals as NtR(0), NtR(1),...".

I believe that it should say "that there is NOT a way to "count" ...". 

Thanks!

**Comment by boazbk** [comment]
You're right - thanks! If you tell me your name I will add you to the acknowledgements.

**Comment by JasonMa2016** [comment]
Jason Ma. Thank you!
