### ISSUE TITLE
[Introduction] Eratosthenes

### ISSUE THREAD

**Issue by SmedbergM** [boazbk/tcs#161]
**Chapter name**: Introduction

**List of bugs/typos**
1. 
> Eratosthene

should be
> Eratosthenes

2. 
> the precursors of "standard algorithms"

should be
> the precursors of the "standard algorithms"

3. 
> multiplying 64 bit or 20 digit

should be
> multiplying 64-bit or 20-digit

4. 
> multiplying two $n$ digit numbers

should be
> multiplying two $n$-digit numbers

**Comment by boazbk** [comment]
Thanks for fixing this!!
