### ISSUE TITLE
[Introduction] "big Oh" inconsistency

### ISSUE THREAD

**Issue by SmedbergM** [boazbk/tcs#164]
**Chapter name**: Introduction, Mathematical Background

**List of bugs/typos**

The text is inconsistent in its usage of the phrase "Big Oh". The most common spelling is "Big Oh", but "big Oh" and "big oh" are also encountered.

Personally, my typographical preference would be (in order)
* Big-$\mathcal{O}$
* Big-$O$
* Big O
* Big Oh
* big O
* others

I prefer the math font because we frequently use Big-$O$ notation in formulas, and it is helpful to use the same fonting in text.

**Comment by boazbk** [comment]
OK accepted your merge, we'll see how it looks. If at some point I see that other texts have another standard I might switch. Thanks!!
