### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by sundogx** [boazbk/tcs#17]
Hi Boaz,

I just wanted to let you know about some typos in lecture notes and problem set 1:

- Figure 3.6 in notes (gradschool --> grade-school)
- 4.1: Two periods in section
- 4.1.1: We can create variables zero and one that are have
4.1.6 Footnote formatting at the end.
Problem Set 1: Problem 2.1: The problem statement and the "In other words" aren't saying the same thing logically. It's not hard to see that the "in other words" is a stronger statement, but it would be nice if "in other words" actually meant they were equivalent.

**Comment by boazbk** [comment]
Thanks! Would you mind telling me your name so I can add you to the acknowledgements?
The gradschool one really seems like a Freudian slip :)

**Comment by sundogx** [comment]
Sure, my name is Alec Sun.
