### ISSUE TITLE
All (Image) Resources

### ISSUE THREAD

**Issue by JZL** [boazbk/tcs#172]
Hi,

I'm really enjoying reading your textbook but would prefer to read it on my kindle during my commute. Is it possible for you to include the `figure` directory in github so I can recompile the LaTeX with kindle-sized pages? (I don't know if there are copyright reasons not to) If it's too much hassle, I can scrape your HTML version but thought it could be useful for others too

The full LaTeX generating script would also be helpful but I imagine it could work okay with relatively straightforward pandoc

Thanks!

**Comment by boazbk** [comment]
Hi,
Right now the set of scripts generating the book is in somewhat fragile state (and requires various dependencies that I don't even remember, so even generating it on a machine different than mine is not super easy), and I also prefer to keep this current repository lightweight and with just the source file.

However, the contents of the current figure directory are here: https://www.dropbox.com/s/ofeau6v6vfb6laq/figure.zip?dl=0 

You should be able to use that and pandoc to generate a kindle friendly. 

In case it helps, I am attaching a zip file containing part of the scripts - the files latex.lua and html.lua that are used to generate the latex and html respectively. These are used as pandoc lua writers.


[pandoc_lua_writers.zip](https://github.com/boazbk/tcs/files/2201416/pandoc_lua_writers.zip)

**Comment by JZL** [comment]
Thanks, that's very helpful
