### ISSUE TITLE
Introduction 0.1 EXTENDED EXAMPLE: A FASTER WAY TO MULTIPLY

### ISSUE THREAD

**Issue by carpathiaxiv** [boazbk/tcs#177]
**Chapter name**: Introduction 0.1 EXTENDED EXAMPLE: A FASTER WAY TO MULTIPLY

**List of bugs/typos**

1. In 1 more place, one of the three products required, $\underline{x}\underline{y}$, were written as $\underline{y}\underline{y}$ -- "Specifically, we can compute $x\times y$ from the three products $\overline{x}\overline{y}$, $\underline{x}\underline{y}$ and $(\overline{x}+\underline{x})(\overline{y}+\underline{y})$)..."

**Comment by boazbk** [comment]
Thanks for fixing!

**Comment by milesfertel** [comment]
Note: This has not been updated in the PDF at https://introtcs.org/public/lnotes_book.pdf or in https://introtcs.org/public/lec_01_introduction.html
