### ISSUE TITLE
Introduction 0.1.1 Beyond Karatsuba’s algorithm 

### ISSUE THREAD

**Issue by carpathiaxiv** [boazbk/tcs#178]
**Chapter name**:  Introduction 0.1.1 Beyond Karatsuba’s algorithm 

**List of bugs/typos**
1. in `Matrix Multiplication (advanced note)`, there might be two typos for the product of x and y. First, the top left component had y1,01. I believe it should be y1,0. Second, the top right component has y1,0. I believe it should be y0,1.

**Comment by boazbk** [comment]
Thanks for fixing!
