### ISSUE TITLE
Introduction 0.5 Exercises Exercise 0.3 Analysis of Karatsuba's Algorithm

### ISSUE THREAD

**Issue by carpathiaxiv** [boazbk/tcs#179]
**Chapter name**:  Introduction 0.5 Exercises Exercise 0.3 Analysis of Karatsuba's Algorithm

**List of bugs/typos**
1.  counter example: say C = 0.1, T(2) = 10, T(4) = 3 * T(2) + 0.1 * 4 = 30.4. Then it does not hold that T(4) <= 10 * C * n^log2(3) = 9.

**Comment by boazbk** [comment]
Can you tell me your full name so I can add you to the acknowldgements?

**Comment by carpathiaxiv** [comment]
Hi Professor,

It's Licheng Xu again. I think you already added my name to the
acknowledgement. I'm flying to Boston tonight and I look forward to seeing
you at the lecture tomorrow!

Best,
Licheng

**Comment by boazbk** [comment]
Thanks!
