### ISSUE TITLE
Lecture 2 pg. 83

### ISSUE THREAD

**Issue by jacobmeyerson** [boazbk/tcs#18]
----> "S = {s_0, s_1,...s_{m-1}}" : since k = |S|, I think it should be: "S = {s_0, s_1,...s_{k-1}}"

----> "If t_j was marked before them we have found" : I think it should be: "If t_j was marked before, then we have found"

----> "in this case E(m) must map" : I think it should be: "in this case E(s_m) must map" (because I'm not sure what E(m) would refer to)

**Comment by boazbk** [comment]
Thank you!!
