### ISSUE TITLE
Chapter 1, Mathematical Background: grammatical errors

### ISSUE THREAD

**Issue by michelle-chiang** [boazbk/tcs#182]
**Chapter name**:  Chapter 1, Mathematical Background

**List of bugs/typos**
1. nit: In the "Aside: mathematical vs programming notation" section, the following sentence has grammatical errors:

> One consequence of that is that in mathematics we often end up reusing **identifier**, and also “run out” of letters and hence use **greek** letters too, as well as distinguish between small and capital letters.

Suggested fix:

> One consequence of that is that in mathematics we often end up reusing **identifiers**, and also “run out” of letters and hence use **Greek** letters too, as well as distinguish between small and capital letters.

**Comment by boazbk** [comment]
Cam you tell me your name so I can add you to the acknowledgements?

**Comment by michelle-chiang** [comment]
Michelle Chiang. Thanks!
