### ISSUE TITLE
Introduction - Typo

### ISSUE THREAD

**Issue by pwatts6060** [boazbk/tcs#184]
**Introduction**

**List of bugs/typos**

1. Section: ON THE IMPORTANCE OF NEGATIVE RESULTS.
Should say "as" not "a"
Current: (This fifth postulate
was known a the “parallel postulate”, and roughly speaking it
states that every line has a unique parallel line of each distance.)
Fixed: (This fifth postulate
was known **as** the “parallel postulate”, and roughly speaking it
states that every line has a unique parallel line of each distance.)

**Comment by boazbk** [comment]
Can you tell me your full name so I can add you to the acknowledgements?

**Comment by pwatts6060** [comment]
Patrick Watts

**Comment by boazbk** [comment]
Thanks!
