### ISSUE TITLE
Mathematical Background

### ISSUE THREAD

**Issue by pGalu** [boazbk/tcs#186]
**Mathematical background**: 

**List of bugs/typos**

1. **Reading mathematical texts**, (example) definition of the complexity class BQP. It says  

> where $F_n:\{0,1\}^n \rightarrow \{0,1\}$ is the restriction of $F$ to inputs of length $\{0,1\}^n$

and I think it should say 

> where $F_n:\{0,1\}^n \rightarrow \{0,1\}$ is the restriction of $F$ to inputs of length $n$

**Comment by boazbk** [comment]
Thanks! Can you tell me your name so I add an acknowledgement?
