### ISSUE TITLE
Chapter 2: Representation, Section 2.1.3

### ISSUE THREAD

**Issue by EmilyYChan** [boazbk/tcs#187]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

Representation

1. We is capitalized in the middle of the sentence: "By adding a little redundancy,
We can do just that in the digital domain"

2. Get is repreated twice: " Using this, we get get a one to one map 𝐸′
∶
({0, 1}∗
) × ({0, 1}∗
) → {0, 1}∗ "

**Comment by boazbk** [comment]
Thanks!
