### ISSUE TITLE
NAND Appendix

### ISSUE THREAD

**Issue by sarahet123** [boazbk/tcs#19]
"The output is the value of the variables y_0, ……, y_⟨𝑚−1⟩⟨m−1⟩. (If a variable of the form y_⟨𝑖⟩⟨i⟩ has not been assigned a value in the program, then its value defaults to 00.)"

The bit in parentheses is inconsistent with needing every output variable to appear in the program.

Sarah Turnill

**Comment by boazbk** [comment]
Thank you -fixed!
