### ISSUE TITLE
Typos in Computation and Representation

### ISSUE THREAD

**Issue by pwatts6060** [boazbk/tcs#191]
Chapter: Computation and Representation

**List of bugs/typos**

1. Typo: "Similarly, we can represent lists of lists and so in particular matrices." 
Suggested: "Similarly, we can represent lists of lists and so on in particular matrices." 
Change: should be "so on in" not "so in"
Section: Representing vectors, matrices, images.

2. Typo: "Thus an image of 𝑛 pixels would be represented of a list of 𝑛 such length-three lists."
Suggested: "Thus an image of 𝑛 pixels would be represented by a list of 𝑛 such length-three lists."
Change: Should be "by a list" not "of a list"
Section: Representing vectors, matrices, images.

3. Possible typo: For example, consider the multiplication function on natural numbers. This is the function 𝑀𝑈𝐿𝑇 ∶ ℕ × 𝑁 → ℕ 
Change: Why is the N symbol in italics rather than as the Natural number symbol? I believe the 3 N symbols should all by the same. 
Section: Distinguish functions from programs

**Comment by boazbk** [comment]
Thanks!
