### ISSUE TITLE
Spell checking typos Introduction and other chapters

### ISSUE THREAD

**Issue by pwatts6060** [boazbk/tcs#192]
Introduction

**List of bugs/typos**

1. Chapter: Introduction
Section: N/A
Text: "(which is more than three millenia!) to compute the same result."
Suggested: "(which is more than three millennia!) to compute the same result."
Change: Incorrect spelling. 'millenia' should be  'millennia'.

2. Chapter: Introduction
Section: Further Explorations (right at the end)
Text: "going back to the ancient greeks)"
Suggested: "going back to the ancient Greeks)"
Change: greeks should be capitalized as Greeks.

3. Chapter: Introduction
Section: 
Text: "Part IV: Randomized computation: Probability, randomized algorithms,
BPP, amplification, ...[OMITTED]..., pseudrandom generators
and derandomization."
Suggested: "Part IV: Randomized computation: Probability, randomized algorithms,
BPP, amplification, ...[OMITTED]..., pseudorandom generators
and derandomization."
Change: Incorrect spelling. 'pseudrandom' should be  'pseudorandom'. Missing an 'o'.

3.1. Chapter: Cryptography
Section: Public key encryption, trapdoor functions and pseudrandom
generators
Text: The actual Section heading: "Public key encryption, trapdoor functions and pseudrandom
generators"
Suggested: "Public key encryption, trapdoor functions and pseudorandom
generators"
Change: Incorrect spelling. 'pseudrandom' should be  'pseudorandom'. Missing an 'o'.

4. Chapter: Mathematical Background
Section: Directed graphs. definition
Text: "If the edge 􀔤⃗⃗⃗⃗⃗􀔥⃗⃗⃗ is present in the graph then we
say that 􀔥 is an out-neighbor of 􀔤 and 􀔤 is an in-neigbor of 􀔥."
Suggested: If the edge 􀔤⃗⃗⃗⃗⃗􀔥⃗⃗⃗ is present in the graph then we
say that 􀔥 is an out-neighbor of 􀔤 and 􀔤 is an in-neighbor of 􀔥.
Change: Incorrect spelling. 'in-neigbor' should be 'in-neighbor'. Missing an 'h'.

5. Chapter: Computation and Representation
Section: Representing natural numbers
Text (side note): "We chose the particular
representation above for the sake of simplicity,
so the the 􀖄-th bit"
Suggested: "We chose the particular
representation above for the sake of simplicity,
so the 􀖄-th bit"
Change: Remove repeated the. "the the" to "the".

6. Chapter: Computation and Representation
Section: Representing a rational number as a string
Text: "In our convention, we represent
19 as the string 11001 and 236 as the string 00110111, and so we
could rerpresent" 
Suggested: "In our convention, we represent
19 as the string 11001 and 236 as the string 00110111, and so we
could represent" 
Change: Incorrect spelling. 'rerpresent' should be represent''. 

7. Chapter: Computation and Representation
Section: Representing natural numbers
Text: "is the first letter in the Hebrew alphabet, and called
the the next largest infinite number by"
Suggested: "is the first letter in the Hebrew alphabet, and called
the next largest infinite number by"
Change: Remove repeated the. "the the" to "the".

8. Chapter: Computation and Representation
Section: Representing graphs
Text: "That is, we identify the vertex set 􀔋 of a graph with the set
[􀔝] where 􀔝 = |􀔋 |, and represent the graph 􀓼 = (􀔋 , 􀓺) a a list of 􀔝
lists, where the 􀔘-th list consists of the out-neighbors of vertex 􀔘."
Suggested: "That is, we identify the vertex set 􀔋 of a graph with the set
[􀔝] where 􀔝 = |􀔋 |, and represent the graph 􀓼 = (􀔋 , 􀓺) as a list of 􀔝
lists, where the 􀔘-th list consists of the out-neighbors of vertex 􀔘."
Change: Replace "a a" with "as a"

9. Chapter: Computation and Representation
Section: Advanced note: beyond computing functions
Text: "Later on in this course we will consider even more general tasks, including
interactive tasks, such as finding good strategy in a game, tasks
defined using probabilistic notions, and others."
Change: Replace "good strategy" with either "a good strategy" or "good strategies"

10. Chapter: Computation and Representation
Section: After Lemma 2.4 There does exist a one-to-one map
Text: https://i.gyazo.com/38cd12854626c2bea1cdae775b67d4ac.png
Change: Highlighted N should be natural number symbol?

**Comment by boazbk** [comment]
Fixed  - thank you!!
