### ISSUE TITLE
Computation Chapter

### ISSUE THREAD

**Issue by EmilyYChan** [boazbk/tcs#193]
There were too many errors to list individually where they all are, but they shouldn't be hard to find using ctrl-F (I read the html version):

1. "applications of a function in \{ AND, OR , NOT \}{AND,OR,NOT} to **omputs** or previously computed values."
2. "Eqmajusing"
3. "\eqref{{eqmajusingandor}}"
4. "NAND(NAND(NAND(NAND(a,b),NAND(a,c)),NAND(NAND(a,b),NAN" -- this expression is cut off
5. "We will see more example(**s**) of the power of simple operations like NAND"
6. crabfig link doesn’t lead anywhere
7. "gadget that ensures that at most one marble flows in each **wire**. " -- should wire be tube?

**Comment by boazbk** [comment]
Thank you! I've now fixed all the HTML links.
