### ISSUE TITLE
Page 103, Definition 3.2

### ISSUE THREAD

**Issue by JasonMa2016** [boazbk/tcs#20]
On the third line of the definition, I believe that it should say $l \in [s]$, instead of s+1. The line above defines s as |L|; however, [s+1] = {0,...,s}, which is |L|+1.

**Comment by boazbk** [comment]
The "program counter" in a configuration actually has |L|+1 values.
This is because it starts in value 0, which is just before the first line is executed, and ends in value |L|, which is just after the last line is executed.
Does this make sense?

**Comment by JasonMa2016** [comment]
Got it!
