### ISSUE TITLE
Loops and Infinity Typo

### ISSUE THREAD

**Issue by shaandsingh** [boazbk/tcs#200]
**Chapter name**: Loops and Infinity

**List of bugs/typos**

In the Turing Machines section, the caption under the mural painted by grad students at the University of Washington says this: "Steam-powered Turing Machine mural, painted by CSE grad students the University of Washington on the night before spring qualifying examinations, 1987."

It's missing "at" after "students" and before "the."

**Comment by boazbk** [comment]
Thanks!!
