### ISSUE TITLE
Equivalent models of computation

### ISSUE THREAD

**Issue by pGalu** [boazbk/tcs#202]
**Equivalent models of computation, Recursion in NAND« (advanced note)**:

**List of bugs/typos**

1. The code for implementing the stack operation `push(foo)` is 
```
Stack[stackpointer] = foo
foo += one
```
and should be
```
Stack[stackpointer] = foo
stackpointer += one
```
2. "Enhanced" lambda calculus, definition of simplification of a $\lambda$ expression.
It says:

> 1. _(Evaluation / $\beta$ reduction.)_ If the expression has the form $(exp_L exp_R)$ then replace the expression with $exp'_L[x \rightarrow L]$.

and I think it should say

> 1. _(Evaluation / $\beta$ reduction.)_ If the expression has the form $(exp_L exp_R)$ then replace the expression with $exp'_L[x \rightarrow exp_R]$.

**Comment by boazbk** [comment]
Thanks!
