### ISSUE TITLE
Chapter 3: Computation -- Definition Issues

### ISSUE THREAD

**Issue by singerng** [boazbk/tcs#203]
**Chapter name**: Computation

Reposting from later comments on https://github.com/boazbk/tcs/issues/190 -- issues with definition of computing a NAND function.

The definition of computing a function via a NAND program appears to be incomplete. Here's the relevant portion of the text:

> 
> Let F : {0,1}^n -> {0,1}^m be some function, and let P be a NAND program. We say that P computes the function F if:
> 
> P has n input variables X[0], ..., X[n-1] and m output variables Y[0], ..., Y[m-1].
> For every x in {0,1}^n, if we execute P when we assign to X[0], ..., X[n-1] the values x_0, ..., x_{n-1}, then at the end of the execution, the output variables Y[0], ..., Y[m-1] have the values y_0, ..., y_{m-1}.
> 
> 

However, the text never actually defines values y_0, ..., y_{m-1} relative to F, the function being computed.

Fix: Either write F(x)0, ..., F(x){m-1} instead of y_0, ..., y{m-1}, or add an extra clause letting y = F(x).

Also, in the algorithm for computing increments, the number of steps is messed up; it appears as 1 2 1 2 1, whereas it should probably be 1 2 a b 3.

**Comment by boazbk** [comment]
Thanks! Hopefully will manage to fix the number of steps thing too, this is one of the places where using markdown instead of latex can sometimes be a headache.
