### ISSUE TITLE
Chapter 8: Uncomputability -- Theorem Statement

### ISSUE THREAD

**Issue by singerng** [boazbk/tcs#204]
**Chapter name**: Uncomputability

**List of bugs/typos**

- The text, when proving that MONOTONE is a non-trivial semantic property, states:

> The program INF that simply goes into an infinite loop satisfies MONOTONE(INF)=MONOTONE(INF)=1, since there are no inputs x, x' on which INF(x)=1 and INF(x')=1.

This is a typo; in order for MONOTONE(INF) to be 0, we'd need

> There are no inputs x, x' on which INF(x)=1 and INF(x')=0.

It would also be helpful to add a clarifying phrase like:

> (In fact, INF is the ultimate partial function -- INF(x) is not defined for any x!)

- I also found the proof of the uncomputability of ZEROFUNC to be very difficult to parse because the algorithm B that would compute HALTONZERO is incompletely defined at the beginning of the proof and only fully defined at the very end of the proof. First, it states:

> Given a program P, Algorithm B will construct the following program P': on input x \in \{0,1\}^*, P' will first run P(0), and then output 0.

Not until the end of the proof is the crucial element of the definition of B mentioned that

> Thus if we define algorithm B as B(P)=A(P') (where a program P is mapped to P' as above) then we see that if A computes ZEROFUNC then B computes HALTONZERO.

It would make more sense to define Algorithm B in a similar way to how it's done in the proof of Rice's theorem:

> Algorithm B(P):
> 1. Given a program P, Algorithm B will construct the following program P': on input x \in \{0,1\}^*, P' will first run P(0), and then output 0.
> 2. Algorithm B will then return the value A(P').

And correspondingly rewrite the second sentence to:

> Thus, since we defined algorithm B such that B(P)=A(P') for all P \in \{0,1\}^* (where a program P is mapped to P' as above) then we see that if A computes ZEROFUNC then B computes HALTONZERO.

- Finally, where the text says

> Hence in this case the program Q has the same functionality as INF. Thus...

and

> Q computes the non-monotone parity function, and we get that...

to use the language introduced in the formal statement of Rice's Theorem regarding "functional equivalence." We could write the two sentences as:

> Hence in this case the program Q is functionally equivalent to INF. Thus, since MONOTONE is a semantic function...

and

> Q is functionally equivalent to PAR, and, since MONOTONE is a semantic function, we get that...

**Comment by boazbk** [comment]
Thank you! These are very useful comments - will fix shortly!
