### ISSUE TITLE
Evaluating the Lookup Function

### ISSUE THREAD

**Issue by captainsn** [boazbk/tcs#205]
I believe there is a typo in the portion of the book that defines how to evaluate the lookup function. The book states that you first need to list out all of the values of the function. For example, for Lookup2,  you would first list: F00, F01, F10, F11. However, I thought that in this course, we are treating the first bit as the least significant bit, in which case F01 and F10 should be switched in the order in which they are listed. Thanks! 

- Sandip Nirmel

**Comment by boazbk** [comment]
Thank you!
