### ISSUE TITLE
Restricted Computational Models Typo

### ISSUE THREAD

**Issue by rxu18** [boazbk/tcs#206]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: Restricted Computational Models

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. In the solution for *Palindromes are not regular*, the sentence "since $xz=1^{n_0-|y|};1^{n_0}$" should be "since $xz=0^{n_0-|y|};0^{n_0}$" to be consistent with the definition of w.

2. Theorem "Equivalence of regular expressions is computable.." has double periods.

3. In the explanation of "base rules" before "Context Free Grammar", Rightarrow1 was printed literally, instead of as a symbol. What you want is probably 𝑛𝑢𝑚𝑏𝑒𝑟 ⇒ 𝑑𝑖𝑔𝑖𝑡 𝑛𝑢𝑚𝑏𝑒r there.

4. In the proof idea for "Fullness of CFG's is uncomputable", the sentence "there is some finite alphabet Σ (containing # and )" should have a ; symbol before the ).

**Comment by boazbk** [comment]
Thank you!

**Comment by ultimaxx9** [comment]
In "Efficient matching of regular expressions (advanced, optional)" memorization is incorrectly spelled "memoization"
