### ISSUE TITLE
Restricted Models: Some Caveats and Clarifications

### ISSUE THREAD

**Issue by singerng** [boazbk/tcs#207]
**Restricted Models**: The names of the chapter and section(s) where the typos/bugs/are. (Please use _names_, not _numbers_, since the numbers tend to change).

**List of bugs/typos**

- In the proof that regular languages can be decided by a halting NAND++ program, the discussion of Case 3, which corresponds to the Kleene star operator, seems to me to be missing a crucial explanation, which is why we only consider partitions of x into at most |x| pieces. The explanation seems to me to go something like this:

> If phi_exp(x) = 1, then we know that for some k, x = x_0 ... x_{k-1}, and phi_exp’(x_0) = ... = phi_exp’(x_{k-1}) = 1. If k > |x|, then at least k - |x| of the strings {x_0, ..., x_{k-1}) must be empty (because otherwise the total length of their concatenation would exceed |k|), and if we just removed those strings from the concatenation, we would still have a partition such that phi_exp(x) = 1. Thus, we need only consider partitions of x into at most |x| pieces.

- The definition of restricted expressions (“we will define exp[sigma] to be the regular expression such that...”) is also slightly confusing to me, because it’s not immediately clear that a restriction is itself a regular expression. I see why this is true, but only because of the claim that is made a few paragraphs later, after talking about how to “compute” exp[sigma].

Perhaps instead of defining restriction as a regular expression and then specifying how to compute it, we could define restrictions formally using the computation as a recursive definition: Something like “More formally, we define exp[sigma] recursively as...”, give the recursive definition, and then make the claim, which shows that it matches with what our intuition says that exp[sigma] should represent.

- In the proof of the pumping lemma, what does "If try to take the minimal such v" mean? What is minimal about v? Are we minimizing |bcd|? Also, how do a and e (from the statement of the lemma) factor in -- we've only mentioned b, c, and d?

**Comment by boazbk** [comment]
Thanks for these comments! We are minimizing the number of steps of derivation.  I have now updated this (still not all of it is compiled but it's in the markdown)
