### ISSUE TITLE
Restricted Computational Models

### ISSUE THREAD

**Issue by janeahn34** [boazbk/tcs#209]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: Restricted Computational Models

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. "cannot result in an finite loop" -> "cannot result in an infinite loop"
Because the Halting problem for Turing-complete computational
models is uncomputable, a system would not be able to verify that a
given program 𝑃 does not halt. For this reason, typical systems for
searching files or databases do not allow users to specify functions
in full-fledged programming languages. Rather, they use restricted
computational models that rich enough to capture many of the queries
needed in practice (e.g., all filenames ending with .txt, or all phone
numbers of the form (xxx) xxx-xxxx inside a textfile), but restricted
enough so that they cannot result in **an finite** loop

2. $$\Phi_exp$ -> $\Phi_{exp}$$
Proof idea  of the theorem that regular expressions always halt, first sentence.

**Comment by boazbk** [comment]
Thanks! Fixed!
