### ISSUE TITLE
Possible Typo In Lecture 3

### ISSUE THREAD

**Issue by Tamox** [boazbk/tcs#21]
![screen shot 2017-09-11 at 11 49 18 pm](https://user-images.githubusercontent.com/6250394/30307399-e8cd8020-974b-11e7-8ea3-96b4859cb7f7.png)

I believe there is a small typo on page 102, definition 3.1. Should it say "Intuitively, the l-th element..." rather than "Intuitively, the l-the element.." on the second line in the screenshot?

**Comment by boazbk** [comment]
It might be a mistake: I am not a native English speaker. What I meant that is that if the ell-th triple equals (u,v,w) then it means that the ell-th line in the program is u := v NAND w.

**Comment by boazbk** [comment]
Now understood what you said - you're of course correct.
