### ISSUE TITLE
Sipser-Gacs Theorem

### ISSUE THREAD

**Issue by mbpereira49** [boazbk/tcs#222]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: Modelling Probabilistic Computation

**List of bugs/typos**

In the proof of Sipser-Gacs Theorem, the statement of Claim II says that the union of the $$S \oplus s_i$$ is a proper subset of {0,1}^m, but in order to imply the theorem I think it should say that the two sets are equal.

**Comment by boazbk** [comment]
You're right - thanks!
