### ISSUE TITLE
Proof of Derandomized Onetime Pad Theorem

### ISSUE THREAD

**Issue by mbpereira49** [boazbk/tcs#225]
Please add your comments here. If you refer to specific chapter or section of the book, please use _names_, and not _numbers_, since the latter tend to change.

Thank you!

The end of the proof of the derandomized onetime pad in the Cryptography chapter was a bit hard to understand in terms of relating equation 20.10 to the definition of the pseudorandom generator. It would help to make clear that the probability that a binary random variable is 1 is the same as the expectation.

**Comment by boazbk** [comment]
Thanks added a clarifications for this (haven't yet compiled it)
