### ISSUE TITLE
[Defining Computation] Figure formatting

### ISSUE THREAD

**Issue by SmedbergM** [boazbk/tcs#227]
**Chapter name**: Defining Computation

**List of bugs/typos**
In Example 3.5 "NAND circuit for XOR", the accompanying figure labels its non-source nodes `0)u`, `1)v`, `2)w`, and `3)y_0`. I suspect that the enumerations were not intended here, and the node labels were supposed to have been TeXified.

**Comment by boazbk** [comment]
This is the way python generates it - perhaps at some later point I will make it with latex but for now will leave it at that - thanks!
