### ISSUE TITLE
roadmapspec link in Prefrace

### ISSUE THREAD

**Issue by orrp** [boazbk/tcs#231]
In [Preface](https://introtcs.org/public/lec_00_0_preface.html), in the final paragraph of [To potential instructors](https://introtcs.org/public/lec_00_0_preface.html#to-potential-instructors), the word roadmapspec is linked to [https://introtcs.org/public/lec_00_0_preface.html#roadmapsec](https://introtcs.org/public/lec_00_0_preface.html#roadmapsec) which redirects to [Preface](https://introtcs.org/public/lec_00_0_preface.html).

**Comment by boazbk** [comment]
Fixed now!
