### ISSUE TITLE
Chapter Syntactic Sugar, And Computing Every Function

### ISSUE THREAD

**Issue by carpathiaxiv** [boazbk/tcs#235]
**Chapter name**: Syntactic Sugar, And Computing Every Function
**List of bugs/typos** when defining the class SIZE, the diagram given has the size all functions from {0,1}^n -> {0,1}^n as c2^n, which is wrong.

**Comment by boazbk** [comment]
Thanks! It got chopped off - will be fixed the next time I compile and push
