### ISSUE TITLE
A few typos in lecture 6a (universality)

### ISSUE THREAD

**Issue by Tuxianeer** [boazbk/tcs#25]
pg 200. middle: "such as i++ (foo) and i- (bar)" -> "such as i++ (foo) and **i--** (bar)"
pg 200. at bottom: "attstart" -> "**atstart**"

pg 201. The definition of PAIR is missing a "**+x**" at the end (otherwise it is certainly not one-to-one and confusing until one reaches exercise 8.1)

pg 205. 8.3.1 "Theorem 14.2" -> "Theorem **8**.2"

**Comment by boazbk** [comment]
Thanks! Can you tell me your name so I can acknowledge you?

**Comment by Tuxianeer** [comment]
No problem :)

I'm Daniel Chiu
