### ISSUE TITLE
Chapter 1:"Mathematical Background"

### ISSUE THREAD

**Issue by asurati** [boazbk/tcs#260]
Mathematical Background => Reading mathematical texts => Definitions:
**List of bugs/typos**

1. Within the remark titled "Ifs and equalities in definitions", a sentence goes _"Since this is the definition of this property, it means that $n$ is in fact a perfect square if and only if $m=k^2$ for some $k\in \N$."_ I think it meant n=k^2, and not m=k^2.

2. Within the same remark, a sentence goes _"We could have also said that we define $n$ to be a perfect square if and only if (or use the abbreviation iff) $n=k^2$ for some $k\in \N^2$."_
The end of the sentence turned k into an ordered pair.

Mathematical Background => Basic discrete math objects => Graphs:
**List of bugs/typos**

1. Within the remark titled "Graph terminology", a sentence goes _"There is an unfortunate
confusion between this tern and the more common..."_
The word term is misspelled as tern.

Thank you.

(Edited)

**Comment by boazbk** [comment]
Thank you! Fixed now in source!
