### ISSUE TITLE
TeX rendering issue in Chapter 1 (Mathematical Background) box titles

### ISSUE THREAD

**Issue by Benjamin-Lee** [boazbk/tcs#265]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: The names of the chapter and section(s) where the typos/bugs/are. (Please use _names_, not _numbers_, since the numbers tend to change).

Mathematical Background (specifically Asymptotics and Big-O notation)

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

In the rendered website, I have identified the following issues:

1. In the title of the `definition 1.19 Big $O$ notation` box, the `$`s are not being rendered properly into TeX.
2. Similarly, in the title of the `remark 20 (Big $O$ and equality)` box, the `$`s are not being rendered properly into TeX.

Screenshot:
![](https://i.snag.gy/jTmowN.jpg)

**Comment by boazbk** [comment]
Thanks  - I am aware of this issue that in the HTML the latex is not rendered in titles of definitions, theorems, sections. (It is fine in the PDF version.) At the moment it seems like somewhat of a pain to fix (the title of the definition is displayed through CSS - not sure if KaTeX - the plugin I am using - can render it) but perhaps at some point will investigate it more.

**Comment by boazbk** [comment]
Am closing this issue since it just seems to be too much work to fix it and the benefit is relatively minor
