### ISSUE TITLE
Chapter 1:"Mathematical Background"

### ISSUE THREAD

**Issue by asurati** [boazbk/tcs#266]
**List of bugs/typos**

1. Mathematical Background -> BASIC DISCRETE MATH OBJECTS -> Undirected Graphs.
> A path in the graph is a tuple $(u_0,\ldots,u_k) \in V^k$.

But that tuple has k+1 elements, while V^k is a set of k-tuples.

2. Mathematical Background -> BASIC DISCRETE MATH OBJECTS -> Directed Graphs.
Same situation as above.

3. Mathematical Background -> EXTENDED EXAMPLE: TOPOLOGICAL SORTING -> Proving the result by induction.
> Just like it should always be clear to which function a line of code belongs to, ...".

The preposition 'to' is used twice.

4. Mathematical Background -> PROOFS -> Hierarchical Proofs (optional).
> The advantage of Lamport’s format is that it is very clear for every sentence in the proof what is the role that it plays.

"The advantage of Lamport’s format is that it is very clear for every sentence in the proof what the role that it plays is.", OR
"The advantage of Lamport’s format is that the role that every sentence in the proof plays is very clear." sound better (at least to me).

Thank you.

**Comment by boazbk** [comment]
Thank you!! Will be fixed
