### ISSUE TITLE
[Chapter 0] "Introduction" - error in Figure 4

### ISSUE THREAD

**Issue by iwob** [boazbk/tcs#267]
In Figure 4 illustrating Karatsuba’s algorithm's work per level, there is at the bottom a text "cn/2^L = 1". L is stated to be equal to log2(n). This means that the text at the bottom should be: "cn/2^L = c".

**Comment by iwob** [comment]
Additionally in the bibliographical notes: "The interesting of the (re)discovery of this algorithm by John Tukey in the context of the cold war is recounted in [..]" - a word seems to be missing after "interesting".

**Comment by boazbk** [comment]
Thanks! Will be fixed in the next compilation
