### ISSUE TITLE
Small typo in Lecture 02, p. 84

### ISSUE THREAD

**Issue by a11i5on** [boazbk/tcs#27]
<img width="500" alt="typo" src="https://user-images.githubusercontent.com/21965538/31285509-7ba27518-aa89-11e7-8a75-e99068bfa2bb.PNG">

Shouldn't the second o_i be prime? It's a small typo, but just thought I would point it out. In addition, should the k at the end be k'? 

In addition, I might be wrong but thought that this j was supposed to be i, keeping in line with previously defined notation: 
<img width="510" alt="typo" src="https://user-images.githubusercontent.com/21965538/31285819-6179eba2-aa8a-11e7-85df-4b626f5ac0af.PNG">

Thank you!

**Comment by boazbk** [comment]
You are right - thanks!
