### ISSUE TITLE
Recursive procedures in 4.1

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#282]
I think it is important to either mention in the prose before it, or to clarify in Theorem 4.1, that there can't be recursively defined procedures (which would no longer be equivalent to NAND-CIRC).

**Comment by evansuva** [comment]
Actually, it just would never finish the transformation to NAND-CIRC, so I guess this doesn't change the power of the language, just means that some NAND-CIRC-PROC programs (if recursive procedure calls are allowed) cannot be converted to NAND-CIRC programs.

**Comment by boazbk** [comment]
Agreed , I used to have a comment like that, am not sure why it got removed. 

More accurately it is actually OK to use recursion if the recursive call is for input length that is strictly smaller since then we are guaranteed that the depth of recursion is finite
