### ISSUE TITLE
Example 4.2 - array indexing

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#285]
I think the array indexing in this example will cause some confusion. The discussion following deals with the unbounded loops and I like the conversion to ADD_n, which makes the loop construct okay, but I think some discussion about the array indexing is also needed. Here, I think the solution (which I believe is done in the circuit shown) is to just consider the inputs and outputs as separate variables for each array element, so when the loop is unrolled there is no need to have a variable-dependent memory access. 

This would lead nicely into the LOOKUP section - although it looks like we needed "lookup" to do array indexing for ADD_n, we don't really need it because none of the data accesses are actually data dependent (once n is fixed).

**Comment by rxu18** [comment]
Good point. I think the conversion to ADD_n is an important concept that can be confusing, and clearer indexing can definitely help.
What do you mean by considering input and output as separate variables?

**Comment by evansuva** [comment]
I mean that instead of considering the input as x and needing to index its elements, the actual inputs for ADD_n are (A0, A1, ..., A_n-1; B1, B2, ..., B_{n-1}) where each of these is the corresponding bit of x and y, and the outputs are Y0, Y1, ..., Y{n}. This is like what the figure 4.4 does - showing A[0] = x[0], B[0] = x[2], A[1] = x[1], B[1] = x[3] as the four input bits and Y[0], Y[1], Y[2] as the three output bits. There is no array indexing going on, just using "x[2]" as a convenient variable name for an input.

**Comment by boazbk** [comment]
I guess the proposal would be to change to the syntax A_i from A[i]? 
I agree there are some advantages in this syntax, but there is also something convenient in using valid Python syntax A[i] which is that it makes it easier to automatically generate the code/circuit of Figure 4.4 from the listing in Example 4.2. (The idea is that basically we redefine NAND(a,b) to take two _strings_ as inputs and print "temp_j = NAND(a,b)" where "temp_j" is a new temporary variable. Once we do this, we can simply run ADD on the inputs "X[0]",....,"X[2n-1]" and it will essentially print out the code you see in Figure 4.4.) 

Maybe it would help if I added some clarifying text saying that while we use Python syntax for convenience, for every choice parameter n, ADD_n is a _finite_ function taking 2n inputs which we denote by A[0] ... A[n-1], B[0],...,B[n-1]  and outputting n+1 ouputs Result[0] ...  Result[n] ?

**Comment by evansuva** [comment]
I think its okay to keep the python array indexing syntax, but to add an explanation that this code only uses indexing with constant-value indexes (with the loop unrolled, etc.) so can be done simply with a circuit. Your second paragraph there sounds good to me.
