### ISSUE TITLE
4.8 In defense of Fortran

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#288]
I'm not sure where the oft-repeated claim that Fortran I didn't support user-defined functions came from, but I'm pretty sure it is not true. (My first internship was with John Backus at IBM Almaden, so I feel obligated to defend Fortran whenever I can.) See for example, (1956 Fortran manual, earliest I can find easily on-line)
https://archive.computerhistory.org/resources/text/Fortran/102649787.05.01.acc.pdf
Page 13 talks about "built-in functions", and then has a section on loading functions from library tapes and how any routine can be complied into a closed subroutine. (Obviously, not quite the convenience we are used to today, but definitely still a notion of user-defined functions.)

**Comment by boazbk** [comment]
It seems like you're right - happy to drop it. Feel free to do it or I can do it myself.
 I think I've seen this claim in more than one place. In particular Wikipedia says here ( https://en.wikipedia.org/wiki/Fortran#FORTRAN ):

IBM's FORTRAN II appeared in 1958. The main enhancement was to support procedural programming by allowing user-written subroutines and functions which returned values, with parameters passed by reference. The COMMON statement provided a way for subroutines to access common (or global) variables. Six new statements were introduced:[18]

SUBROUTINE, FUNCTION, and END
CALL and RETURN
COMMON

**Comment by evansuva** [comment]
I don't know the details, and I'm sure there were changes to make user-defined functions more convenient. The more interesting limitation of Fortran was not allowing recursive functions, which I think was true until 1990.
