### ISSUE TITLE
Difficult broken references in chapters up to "Efficient Computation"

### ISSUE THREAD

**Issue by rxu18** [boazbk/tcs#292]
Sorry for putting all of them in the same issue, but opening all of these would likely be harder to track.

These are issues with broken links in the first 10 chapters. I did some investigation for each, and either fixed the issue or pinpointed the line causing the problem. The links fixed are in a PR. Here are the ones I cannot fix.

* 3.776 (A circuit with NAND gates): the figure is not rendering. Does the reference picture ../figure/nandcircxor.png still exist?
* 3a.504 (Table: An example of a function): the .table definition has a syntax error and spills into the book.
* 7.539: The line is not being rendered, which causes a broken link. Does the reference picture ../figure/Rule110Big.jpg still exist?
* 8.250 (many texts use the "language" terminology): [decidablelanguages](){.ref} is broken. Is the reference removed?
* 8.516 (eat your cake and have it too): [defalgsec](){.ref} is broken. Is the reference removed?
* 9.481 (Expression for computing the index): [computeidx-ex](){.ref} is broken. Is the referenced problem removed?

**Comment by rxu18** [comment]
@boazbk some of them are. Thanks for sharing the build environment with me -- I will go an check these soon.

**Comment by boazbk** [comment]
Hi @rxu18  - could you open a new issue for the ones that are still alive? thanks!

**Comment by rxu18** [comment]
Yes! Having half a year more of experience makes a bunch of these issues easy, so I'll just fix them.
