### ISSUE TITLE
Typos in Chapter 0: Introduction

### ISSUE THREAD

**Issue by kfuruie** [boazbk/tcs#301]
**Chapter name**: Introduction

**List of bugs/typos**

1. At the end of the first sentence under **Integer multiplication: an example of an algorithm** "representing numbers is known a data structure" should be "representing numbers is known **as** a data structure"

**Comment by kfuruie** [comment]
2. Above **Extended Example: A faster way to multiply (optional)** in **Remark 0.3 (Specification, implementation and analysis of algorithms.) under the **Analysis** heading, the first sentence "why does this sequence of instructions **achieves** the desired task." has an extra s in achieve and should be "why does this sequence of instructions **achieve** the desired task.

**Comment by rxu18** [comment]
I see the changes are merged. Close the issue?

**Comment by boazbk** [comment]
Yes - thanks!
