### ISSUE TITLE
Chapter: Computation and Representation, Section: Representing natural numbers

### ISSUE THREAD

**Issue by scottsalvaggio** [boazbk/tcs#315]
**Chapter name**: Computation and Representation
**Section**: Representing natural numbers

**Text says:** For example, we represent the number six as the string $110$ since $1\cdot 2^{2} + 1 \cdot 2^1 + 0 \cdot 2^0 = 6$, and similarly we represent the number thirty-five as the string $y = 100011$ which satisfies $\sum_{i=0}^5 y_i \cdot 2^{|y|-i} = 35$.

**Suggested correction:** ... which satisfies $\sum_{i=0}^5 y_i \cdot 2^{|y|-i-1} = 35$.

**Comment by rxu18** [comment]
Indeed. Since we index from $0$, it should be $2^{|y|-i-1}$. Making a PR right now.

**Comment by boazbk** [comment]
Thanks @rxu18  & @scottsalvaggio !
