### ISSUE TITLE
Code and Data

### ISSUE THREAD

**Issue by emilyjia** [boazbk/tcs#318]
**Chapter name**: Code and Data

**List of bugs/typos**

1. In introduction, the paragraph starting with "In this chapter, we will begin to explore", there is a sentence "The number 100 hear is somewhat arbitrary and fixed for concreteness" which should have "here" not "hear"

2. In the list of tuples representation, X[i] and Y[j] are used without defining X, Y. It's worth reminding the student what X, Y are since you are already introducing so much new notation. 

3. In the paragraph after equation 5.1 "We can represent P as a string..." I think it's worth writing "We can represent P = (n, m, L) as a string" to remind the reader of where n, m come from. 

4. After take-away points on EVAL_{s, n, m}, the term self circularity is used and italicized but the meaning is not clear. "One of the first examples of self circularity we will see in this book"

**Comment by rxu18** [comment]
Thanks! Working on them rn.

**Comment by boazbk** [comment]
Thanks @emilyjia  and @rxu18 !
