### ISSUE TITLE
Defining Computation: The NAND function - MAJ expression and figure mismatch

### ISSUE THREAD

**Issue by Michael9094** [boazbk/tcs#320]
At the end of the intro, the expression NAND(NAND(NAND(NAND(a,b),NAND(a,c)),NAND(NAND(a,b),NAND(a,c))),NAND(b,c))
and the figure "A circuit with NAND gates to compute the Majority function on three bits" don't seem to match.  The expression has 9 NANDs, but the figure has 15 NAND gates.

**Comment by boazbk** [comment]
You are right - thanks! Will update to the following figure in the next time I compile 

![majfromnand](https://user-images.githubusercontent.com/5474168/64986649-7c617800-d895-11e9-998a-ee916c439040.png)
