### ISSUE TITLE
Typo, Example 3.1 (3.6)

### ISSUE THREAD

**Issue by panieldark** [boazbk/tcs#330]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

Defining Computation (3): 
Example 3.1, (3.6)
MAJ is defined as MAJ(x0,x1,x2), but has an x3 as one of the variables.

<img width="942" alt="Screen Shot 2019-09-17 at 11 05 50 PM" src="https://user-images.githubusercontent.com/21699995/65186040-c33aa380-da36-11e9-8704-59d2489de1cc.png">

**Comment by boazbk** [comment]
Thanks! Someone (you?) seems to have fixed it
