### ISSUE TITLE
Bug in written code, 3.3.2 "Equivalence of circuits and straight-line programs"

### ISSUE THREAD

**Issue by panieldark** [boazbk/tcs#332]
The bugged 8-line code occurs right before the text "We can also present this 8-line program as a circuit with 8 gates, see Fig. 3.12."

The code compares a 2 bit number, and outputs a 1 only when x_0 x_1 is greater than x_2 x_3. However, with the code expressed, an input of x_0 = x_1 = x_2 = x_3 = 1 outputs a 1, when it should not (since 3 is not greater than 3). 

<img width="258" alt="Screen Shot 2019-09-18 at 5 57 16 PM" src="https://user-images.githubusercontent.com/21699995/65189178-3dbaf180-da3e-11e9-95f4-ea8ad5f92d51.png">

Again, hope this helps!

**Comment by boazbk** [comment]
Thanks! Seems to be fixed - maybe by @rxu18 ? The code
temp_1 = NOT(X[2])
temp_2 = AND(X[0],temp_1)
temp_3 = OR(X[0],temp_1)
temp_4 = NOT(X[3])
temp_5 = AND(X[1],temp_4)
temp_6 = AND(temp_5,temp_3)
Y[0] = OR(temp_2,temp_6)

works. I will also be updating the figure in the next compilation
