### ISSUE TITLE
Ch 2, computation and representation

### ISSUE THREAD

**Issue by coderigo17** [boazbk/tcs#333]
Perhaps a small typo in the proof for the uncountability of the reals? 

"Consider the lexicographic ordering of the binary strings (i.e., "", 0,1,00,01)... in this order. That is, x_0 = "", x_1 = 0, x_2 = 00 and so on..."

I think it should be x_2 = 1, whereas x_3 = 00? Hopefully I'm not just misunderstanding :)

**Comment by boazbk** [comment]
Thanks!
