### ISSUE TITLE
Chapter 3, Solved Exercise 3.4 Solution

### ISSUE THREAD

**Issue by ted-palmer** [boazbk/tcs#334]
Hi! I discovered that there was a problem with the solution to exercise 3.4, the problem that asks you to write a function to compare two binary strings. If the first number is 01 and the second number is 10, it will output 1 even though the second number is greater than the first. There is another case when the first number is 10 and the second number is 11, it will also output 1 when it should not. I have attached a boolean circuit that should solve the problem.  Please let me know if this helps! Thanks!

<img width="991" alt="figure 3 12" src="https://user-images.githubusercontent.com/41527174/65211783-f0567880-da6d-11e9-9cfa-fa028de4328c.png">

**Comment by boazbk** [comment]
Thanks! I've now fixed it by using my code2circuit  notesbooks on https://github.com/boazbk/tcscode

![comparecircuit](https://user-images.githubusercontent.com/5474168/65281956-bdf65b00-db01-11e9-84fd-328ac5256544.png)
