### ISSUE TITLE
Figure 3.12 & Solution 3.3.2

### ISSUE THREAD

**Issue by jac3rd** [boazbk/tcs#342]
I believe I've found an error in the textbook.
According to Solution 3.3.2, the Boolean circuit below (figure 3.12) represents the CMP function (Solvedexercise 3.4), where:
CMP : {0,1}^4 returns 1 if (x[0], x[1]) > (x[2],x[3]), and 0 otherwise, where (a, b) = 2*a + b;
Assume that the below Boolean circuit is a valid circuit for the CMP function.
Let's step through the evaluation of the input {1,1,1,1}:
-all 3 NOT gates: {1} -> {0}
-top OR gate: {1, 0} -> {1}
-middle OR gate: {0, 1} -> {1}
-bottom OR gate: {1, 0} -> {1}
-AND gate: {1,1} -> {1}
-last OR gate {1,1} -> {1}
CMP : {1,1,1,1} -> {1}, which implies that (1,1)=3 > (1,1)=3,
which we know to be false.
Therefore, we can conclude that the below Boolean circuit is not a valid circuit for the CMP function.
![3_12](https://user-images.githubusercontent.com/46491149/65641057-cfd07600-dfb9-11e9-8f54-61c2febdad6c.png)

**Comment by boazbk** [comment]
I believe this is now fixed in the latest version - thanks!
