### ISSUE TITLE
Chapter 4, Exercise 4.5 (part 3)

### ISSUE THREAD

**Issue by NeejWeej** [boazbk/tcs#343]
**Chapter name**: Chapter 4, Exercise 4.5 (Half and Full Adders) (Part 3)

**List of bugs/typos**
1. In part 3 of the question in Chapter 4 regarding Half and Full Adders, I believe there is an error in the definition of the ADD_n function. The question states that:
 "ADD_n :{0,1}^{2n}  →{0,1}^{n} is the function that outputs the addition of two input n-bit numbers." 
![exercise_4 5](https://user-images.githubusercontent.com/24299285/65709041-e6300d80-e05d-11e9-80b0-c1b364cbec9d.JPG)

However, for ADD_n to allow for the addition of any two n-bit numbers, the output must map to {0,1}^{n+1} to account for overflow if the n bit numbers sum to a number greater than or equal to 2^{n} (which needs at least n+1 bits to represent). For example: 1+1=10, so ADD_n(1,1)=10.

**Comment by SimonsVault** [comment]
I believe you're correct, also the codomain of the full adder should be $\{0,1\}^2$. Do you want to open a pull request? I can also patch it in my open one :)

**Comment by NeejWeej** [comment]
Sorry for the late reply. I opened a pull request that incorporated both of these changes (my first one!). Thank you for your help!
