### ISSUE TITLE
Potential Typo in 3.4.4

### ISSUE THREAD

**Issue by p1ckett** [boazbk/tcs#353]
Hello, 
The first sentence in 3.4.4 of the book says, "Cellular automata is a model of a system composed of a sequence of cells, which of which can have a finite state," and I believe that it should say "**each** of which can have a finite state" rather than "which of which." Obviously a very minor typo, but I thought I'd report it for the sake of clarity.

Thanks

**Comment by aadibajpai** [comment]
You could open a pull request to fix it :)

**Comment by boazbk** [comment]
Fixed by someone - thanks!
