### ISSUE TITLE
F vs f

### ISSUE THREAD

**Issue by jrdek** [boazbk/tcs#357]
(section: Mathematical Background -> Basic Discrete Math Objects -> Sets -> Functions)

Is there any particular reason why both _F_ and _f_ are used as names of functions in this section? It's not incorrect, but it would be somewhat clearer if only one of the two were used.

Thanks!

**Comment by boazbk** [comment]
I try to stick to the convention that lowercase names like f are used for finite functions that take an input of fixed length, while uppercase names like F are used for functions whose input is a string of arbitrary length. If you see examples of cases where I confused the two please do open an issue or pull request - thanks!
