### ISSUE TITLE
Potential Typo in Solution 3.2.2

### ISSUE THREAD

**Issue by nickhayeck** [boazbk/tcs#358]
Solution 3.2.2 states:
> Addition modulo two satisfies the same properties of associativity `(a+b)+c = (a+b)+c` and commutativity `a+b = b+a` as standard addition.

I believe that the equation regarding associativity should read:
> Addition modulo two satisfies the same properties of associativity `(a+b)+c = a+(b+c)` and commutativity `a+b = b+a` as standard addition.

_---Nicholas Hayeck_

**Comment by boazbk** [comment]
Right! Will be fixed in next compile
