### ISSUE TITLE
Potential Improvement to Definition 3.6 (Computing a function via Boolean Circuits)

### ISSUE THREAD

**Issue by nickhayeck** [boazbk/tcs#359]
The last line of the definition reads:
>Let `f : {0,1}^n --> {0,1}^m`. We say that the circuit `C` computes `f` if for every `x ∈ {0,1}^n` , `C(x) = f(x)`.

For purposes of precision and clarity I would suggest:
> For some Boolean function, `f : {0,1}^n --> {0,1}^m`. We say that the circuit `C` computes `f` if and only if  `C(x) = f(x)` for all `x ∈ {0,1}^n`.

_--- Nicholas Hayeck_

**Comment by boazbk** [comment]
As in many mathematics texts, we use "if" in the context of definition to define a notion rather than "if and only if". This is similar to how we say in definition "let x = 17" using equality for assignments.

**Comment by nickhayeck** [comment]
Okay, that makes sense. My apologies!

**Comment by boazbk** [comment]
No need to apologize! This is in fact a common confusion, and I am never sure how to address it - to use "iff"s everywhere, or to try to emphasize it more. At some point I think I had a remark about this, but am not sure if I removed it or not. (There's always the tradeoff of not wanting to have too many footnotes or remarks.)
