### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [boazbk/tcs#362]
The website doesn't support IPv6.

Since it seems to use Netlify, it's necessary click "Enable IPv6" for the domain(s) under DNS management ([per Netlify's IPv6 announcement](https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/#are-we-there-yet)).

**Comment by boazbk** [comment]
Done! I trust you that it's a good thing :)
