### ISSUE TITLE
Exercise 3.10 (Bound on universal basis size)

### ISSUE THREAD

**Issue by SimonsVault** [boazbk/tcs#363]
I'm a bit confused about the exercise "Bound on universal basis size" in chapter "Defining computation".
It asks us to proof "that for every subset B of the functions from {0, 1}^k to {0, 1}, if B is universal
then there is a B-circuit of at most O(k) gates to compute the NAND function". I think there should even be a B-circuit of at most 16 gates, because there are only 16 functions from {0, 1}^2 to {0, 1}.
Am I wrong or is the exercise phrased misleadingly?

**Comment by boazbk** [comment]
Number of gates in a circuit is its size - it’s not the number of unique gates

**Comment by SimonsVault** [comment]
Yes, I understand that. To expand a bit on my reasoning: Because we can use the output of a gate multiple times, it's redundant to have two gates that compute the same function of the input of the circuit. Thus, a circuit with input in {0, 1}^2 would never "need" more than 16 gates (except maybe as output gates).

**Comment by boazbk** [comment]
Ah, I think I see your point - you might be right. Should modify this to be O(1)

**Comment by boazbk** [comment]
Fixed now - thanks!
