### ISSUE TITLE
Strange page break at 'Approximate counting if P = NP' in 'What if P equals NP?'

### ISSUE THREAD

**Issue by shiatsumat** [boazbk/tcs#365]
Thank you for this great textbook!

Let me report a minor issue.
In the pdf version of 'What if P equals NP?', the theorem 'Approximate counting if P = NP' has a strange page break.

**Comment by boazbk** [comment]
You're right - it is a strange page break. I now made some edits in this area and I hope it will go away on its own, since I don't really know why it's there
