### ISSUE TITLE
Typo in proof of Theorem 5.5

### ISSUE THREAD

**Issue by natebrunelle** [boazbk/tcs#379]
In Theorem 5.5 (size hierarchy theorem) there is an expression that should read (assuming latex) "0.1 \cdot \frac{2^n}{n}". Instead, it reads as 0.12 with a dot over the 2. Here is a screenshot of the text with the typo.
![image](https://user-images.githubusercontent.com/509517/66724008-64c2d400-edee-11e9-8235-b2f156f41963.png)

**Comment by boazbk** [comment]
Fixed now - thanks!
