### ISSUE TITLE
section 13.1 3sat example polynomial time reductions

### ISSUE THREAD

**Issue by laurachapman** [boazbk/tcs#388]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: Polynomial Time Reductions

**List of bugs/typos** 

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. Section 13.1 has an example of 3SAT that has the "and" and "or" symbols mixed up

**Comment by boazbk** [comment]
Thank you! Will try to make an issue pass late this week or next week
