### ISSUE TITLE
confusing symbol

### ISSUE THREAD

**Issue by ftr3vf** [boazbk/tcs#393]
In theorem 5.5 in chapter 5 I see that the symbol for subset is a little confusing in that the line under it has a slash. Normally for not subset it would be through the whole thing and this could be confusing as if you are trying to indicate subset remove the slash and for not in subset put a slash through the whole thing. I was confused reading this and did not know which was which.

**Comment by boazbk** [comment]
This means that this is a strict subset (that is $A \subsetneq B$ if $A$ is a subset of $B$ that is not equal to $B$). I added clarification for this symbol in the math background section (will be there in the next time I compile).
