### ISSUE TITLE
TCS Code as data, data as code typo

### ISSUE THREAD

**Issue by kathryn-smith** [boazbk/tcs#395]
Chapter 5, Code as data, data as code

1.Section 5.4 A NAND-CIRC INTERPRETER IN NAND-CIRC:
In the paragraph right above the bolded "Take Away Points" and after the definition of the EVAL function, it states
"Otherwise, EVAL𝑠,𝑛,𝑚(𝑝𝑥) equals 0^𝑚 (this case is not very important: you can simply think of 0^𝑛 as some “junk value” that indicates an error)."
I think the 0^n in the second term should be 0^m, as 0^n is never mentioned anywhere before this.

**Comment by boazbk** [comment]
You are right but I think this is already fixed in the current version
