### ISSUE TITLE
Ch 6: Oblivious Turing Machines exercise typo

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#397]
"That is, we say that $M$ is oblivious if there existe" =>
"That is, we say that $M$ is oblivious if there exists"

**Comment by boazbk** [comment]
Couldn't find it - is this already fixed in the current version?

**Comment by evansuva** [comment]
Not in the version I'm looking at:
https://github.com/boazbk/tcs/blob/master/lec_06_loops.md
search for 'oblivious' and you'll find the problem in the exercise
{.exercise title="Oblivious Turing Machines (challenging)" #obliviousTMex} 
should also 
"head movement are independent " => "head movements are independent "

**Comment by boazbk** [comment]
Right sorry I looked in the wrong chapter - I have another exercises that asks also about the overhead of the simulation in the chapter defining P EXP etc.
