### ISSUE TITLE
Figure 14.10

### ISSUE THREAD

**Issue by randyyan2000** [boazbk/tcs#414]
I believe that the figure in section 14.6 Wrapping Up (attached below) has a slight issue in that the NP set is not entirely contained in EXP when it is proven in the chapter that NP is a proper subset of EXP.

![image](https://user-images.githubusercontent.com/20746298/68896469-85d25980-06f9-11ea-9965-1ef9d3ffeda7.png)

**Comment by boazbk** [comment]
You're right! Will fix in next compile - thanks!
