### ISSUE TITLE
What if P equals NP

### ISSUE THREAD

**Issue by emilyjia** [boazbk/tcs#415]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: What if P equals NP

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. algorithm for FIND_v: search to reduction is missing linebreaks

**Comment by rxu18** [comment]
I'm not familiar enough with formatting to fix this. @boazbk any ideas?

**Comment by boazbk** [comment]
Will fix - thanks!

**Comment by boazbk** [comment]
Fixed
