### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ChristianMay21** [boazbk/tcs#423]
Some of the hand-drawn images and diagrams could be replaced by carefully made images and diagrams made with image editing software. I have some experience with that, and would be happy to make these changes. I think that, done carefully to make sure that the images don't just become boring flow charts that bore the reader, this could enhance the text and even convey some concepts more easily.

I just wanted to check with you that this was something you were interested in before I began any work on it. I would probably start off with a couple of sample images, allow you to give feedback on those, and repeat until we feel like we've come up with something which is appropriate for and enhances your vision for this text.

**Comment by boazbk** [comment]
Thank you so much for this offer! 
I have been trying to go over the images and convert hand-drawn ones to ones that I make with Powerpoint. I think at this point it might be better for me to keep the control and flexibility of doing it myself than having someone do it professionally, as much as it would likely look better in the other option. Once I think all figures are in final form it may change -  thanks again!

**Comment by ChristianMay21** [comment]
Understood :)
