### ISSUE TITLE
Syntactic sugar, and computing every function: Missing link

### ISSUE THREAD

**Issue by haneulshin1030** [boazbk/tcs#513]
**Chapter name**: Ch 4: Syntactic sugar, and computing every function, Section: 4.4 COMPUTING EVERY FUNCTION

**List of bugs/typos**

1. In the Proof of NAND's Universality, there is a missing link at the end of the following sentence: 

> There was nothing about the above reasoning that was particular to the function 𝐺 of ??.

**Comment by rxu18** [comment]
@boazbk seems to be a bug in the compilation: notice that in the table above, the `{ .table #tablefunctiong }` tag is rendered as plain text. Maybe `.table`is not properly defined?

**Comment by boazbk** [comment]
I will check this - thanks!

**Comment by boazbk** [comment]
Not sure how to fix it so for now just dropped the reference
