### ISSUE TITLE
Code as data, data as code: another small typo

### ISSUE THREAD

**Issue by haneulshin1030** [boazbk/tcs#515]
**Chapter name**: Ch 5 Code as data, data as code, Section 5.4 A NAND-CIRC INTERPRETER IN NAND-CIRC

**List of bugs/typos**

1. In the very beginning of the section where the function EVAL is introduced, the beginning of the sentence

> In particular, for every natural numbers 𝑠, 𝑛, 𝑚 > 0

should be

> In particular, for all natural numbers 𝑠, 𝑛, 𝑚 > 0

**Comment by rxu18** [comment]
Seems to be fixed as of the most recent commit.
