### ISSUE TITLE
Code as data, data as code: small typo in Theorem 5.1

### ISSUE THREAD

**Issue by haneulshin1030** [boazbk/tcs#520]
**Chapter name**: Ch 5: Code as data, data as code, Section 5.1 REPRESENTING PROGRAMS AS STRINGS

**List of bugs/typos**

1. In the statement of Theorem 5.1 — Representing programs as strings,

> There is a constant 𝑐 such that for 𝑓 ∈ SIZE(𝑠), there exists a program 𝑃 computing 𝑓 that whose string representation has length at most 𝑐𝑠 log 𝑠.

should state

> There is a constant 𝑐 such that for 𝑓 ∈ SIZE(𝑠), there exists a program 𝑃 computing 𝑓 whose string representation has length at most 𝑐𝑠 log 𝑠.

**Comment by rxu18** [comment]
Seems fixed as of the most recent commit. Thanks!
