### ISSUE TITLE
NP, NP completeness, and the Cook-Levin Theorem: small typo

### ISSUE THREAD

**Issue by haneulshin1030** [boazbk/tcs#529]
**Chapter name**: Ch 14: NP, NP completeness, and the Cook-Levin Theorem, Section 14.2 FROM NP TO 3SAT: THE COOK-LEVIN THEOREM

**List of bugs/typos**

1. In the first sentence of the section,

> We have seen everal example of problems for which we do not know if their best algorithm is polynomial or exponential, but we can show that they are in NP.

should state

> We have seen several examples of problems for which we do not know if their best algorithm is polynomial or exponential, but we can show that they are in NP.

**Comment by rxu18** [comment]
Seems to be fixed as of the most recent commit. Thanks!
