### ISSUE TITLE
section 14.6 (extended church-turing thesis)

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#53]
some points that would be good to add to this section:
- consequently, the classes P and EXP are robust to the choice of model (provided the model satisfies the ECTT)
- thus we can use high-level descriptions of algorithms, like those given in chapter 13, to determine whether a problem is in P
- P and EXP are also robust to most encoding of inputs (because poly(poly(n)) is also poly(n)), however note the difference between binary and unary inputs (the latter being "pseudopolynomial").

**Comment by boazbk** [comment]
thanks!
