### ISSUE TITLE
Modeling running time: small typos

### ISSUE THREAD

**Issue by haneulshin1030** [boazbk/tcs#531]
**Chapter name**: Ch 12: Modeling running time, Section 12.3 EXTENDED CHURCH-TURING THESIS (DISCUSSION)

**List of bugs/typos**

1. In the following sentence toward the beginning of the section,

> All the current constructions of scalable computational models and programming language conform to the Extended Church-Turing The-sis, in the sense that they can be with polynomial overhead by Turing Machines (and hence also by NAND-TM or NAND-RAM programs).

"programming language" should be made plural (to "programming languages"). Also, I think there might be a missing verb in the second half of the sentence (maybe insert "computed" between "be" and "with"?)

2. In the next sentence, the first letter is not capitalized:

> consequently, the classes P and EXP are robust to the choice of model,

**Comment by rxu18** [comment]
I think for the second part of issue 1, "simulated" may be more appropriate. Thanks!
