### ISSUE TITLE
Chapter 11: Efficient computation

### ISSUE THREAD

**Issue by asurati** [boazbk/tcs#533]
**List of bugs/typos**

1. PROBLEMS ON GRAPHS -> Finding the shortest path in a graph:
The paragraph starts with
>The shortest path problem is the task of, given a graph 𝐺 = (𝑉, 𝐸) and
two vertices 𝑠,𝑡 ∈ 𝑉, to find

Ignoring the clause which begins with the word "given", the sentence reads:
> The shortest path problem is the task of, ... ,to find ..."

Below options may sound better:
> The shortest path problem is the task, ..., of finding ..."
> The shortest path problem is the task, ..., to find ..."

2. Efficient computation -> PROBLEMS ON GRAPHS -> Finding the longest path in a graph:
The first paragraph has a sentence that goes:
> But of graphs can and are used to model a variety of phenomena ...

The "of" seems extraneous.

3. PROBLEMS ON GRAPHS -> Min-Cut Max-Flow and Linear programming:
The third paragraph goes:
> We think of an edge 𝑒 an an ordered pair ...

The second "an" seems to be a misspelled "as".

4. PROBLEMS ON GRAPHS -> A note on convexity:
The third paragraph, which begins with *The minimum cut problem is not a priori*, has a sentence:
>The “max flow min cut” theorem ensuring that this embedding is “tight” in the sense that the minimum “fractional cut” that we obtain through the maximumflow linear program will be the same as the true minimum cut.

Replacing "ensuring" with "ensures" avoids leaving the sentence hanging.

5. PROBLEMS ON GRAPHS -> A note on convexity:
Around the sentence *"For example, one of the basic tasks in machine learning is empirical risk minimization."*, the markdown text reads
> That is, the input is a list of labeled examples $(x_{m-1},y_{m-1}),\ldots,(x_{m-1},y_{m-1})$ ...

Below is likely what was intended:
> That is, the input is a list of labeled examples $(x_{0},y_{0}),\ldots,(x_{m-1},y_{m-1})$ ...

6. BEYOND GRAPHS -> SAT:
The second paragraph has a sentence:
> A satisfying assignment for 𝜑 is a string ... such that if 𝜑 evaluates to True if we assign its variables the values of 𝑥.

The "if", immediately before "𝜑",  seems extraneous.

7. BEYOND GRAPHS -> 3SAT:
The second paragraph has a sentence:
>We do not fully understand the reasons for this phenomenon, though the notions of NP
completeness we will see later does offer a partial explanation.

It seems that "does" refers to the "notions of NP completeness". If NP-completeness is regarded as a single notion, "notions" may change to "notion" to preserve the lack of plurality implied by "does". If there are multiple notions of NP-completeness, "does" may change to "do" to preserve the plurality implied by "notions".

8. BEYOND GRAPHS -> Solving quadratic equations:
Around the middle of the first paragraph, a sentence goes (in markdown):
>Since only $0$ and $1$ satisfy the equation $a^2-a$, this...

The equation being referred to seems to be *$a^2-a=0$*.

9. OUR CURRENT KNOWLEDGE:
A sentence in the middle of the first paragraph has a typo "mentiond":
>Thus the efficient algorithms we mentiond above are ...

**Comment by asurati** [comment]
10. PROBLEMS ON GRAPHS -> Finding the shortest path in a graph:
Algorithm 11.2 "Shortest path via BFS":
>while 𝑆 non empty do

The queue is referred to elsewhere by the name Q (and not S).

**Comment by rxu18** [comment]
1. I think the syntax used by boazbk tends to be "task of finding, given ..., the ...".
7. Went with "notion of NP-completeness" to be consistent with the rest of the book.

Thanks for all the issues!
