### ISSUE TITLE
Reference error in "Modelling Running Time"

### ISSUE THREAD

**Issue by rxu18** [boazbk/tcs#537]
**Chapter name**: Modeling Running Time

**List of bugs/typos**
In the "Timed Universal Turing Machine" section, the reference to a construction of the timed universal TM using reference `timeduniversaltmfig` is broken.

**Comment by marwahaha** [comment]
I think the link is working now. As of writing, it's Figure 13.6.
https://introtcs.org/public/lec_11_running_time.html#timeduniversaltmfig
