### ISSUE TITLE
Add instructions how to run locally

### ISSUE THREAD

**Issue by marwahaha** [boazbk/tcs#548]
Hi!
I'd love to work through some of this material, and suggest changes where I can.
Is there a way to run the book locally?
I'd love if the instructions existed in a place on this repository.

Thanks,
Kunal

**Comment by boazbk** [comment]
Hi,
The repository https://github.com/boazbk/panbook contains the files I use to generate this.
Take a look - it's a bit of a pain to install and run - I hope at some point I can make it more "turnkey" but at the moment even for me it took me a few days to install this on a new PC. 
Boaz
