### ISSUE TITLE
Cantor proof figure differs from text

### ISSUE THREAD

**Issue by marwahaha** [boazbk/tcs#560]
**Chapter name**: Computation and Representation

**List of bugs/typos**
Figure 2.8 at time of writing, which describes Cantor's diagonalization argument, has highlighted StF(1)(3) and so on.
However, the text describes StF(1)(2) and so on as the counterexample to StF being onto.
I am hoping that the text could match the figure.

**Comment by boazbk** [comment]
Should be fixed now
