### ISSUE TITLE
Representation Chapter: Link to Berkeley CS70 lecture is wrong

### ISSUE THREAD

**Issue by marwahaha** [boazbk/tcs#561]
In the remark  2.10 (Generalizing beyond strings and reals),
there is a link to a Berkeley CS70 lecture.
But the link to the lecture is about error correcting codes.
It seems like the links are not static.

Here is an alternate link (from when I was a TA for that course) to Infinity and Countability: https://www-inst.eecs.berkeley.edu//~cs70/su15/notes/n19.pdf
Or maybe you were looking for notes from a particular semester.
Either way, I think the link should be changed.

**Comment by boazbk** [comment]
Thanks! I don’t care so much about the semester so any stable link would
do, though maybe nice to have it from a later offering  if there have been
updates/edits

**Comment by marwahaha** [comment]
How about this one?
http://www.fa19.eecs70.org/static/notes/n10.pdf

**Comment by boazbk** [comment]
Sounds good!
