### ISSUE TITLE
Algorithms of regexp matching seem incorrect

### ISSUE THREAD

**Issue by ksqsf** [boazbk/tcs#570]
Both `Match` and `FMatch` contain code:

   if 𝑥 = "" then return 1 iff 𝑒 = "" ;

IIUC, if input `x` is the empty string, both `Match` and `FMatch` will return 1 only when `e=""`. However, this contradicts the definition of $\Phi_e(x)$, because $\Phi_{a*}("")=1$.

Am I misreading the pseudocode?

**Comment by ksqsf** [comment]
A quick fix that looks like right to me is

```
if 𝑥 = "" then return 1 iff 𝑒 = "" or 𝑒 = (c*);
```

because since `Restrict` is correct, the only case that needs to be considered is the empty string, for it can't be matched by a restricted regexp.

PS: the recursive call to `FMatch` should be `x_0...x_{n-2}`.

**Comment by boazbk** [comment]
You are right - thanks! I just updated this.
I added a separate exercise to show that one can design a recursive function MatchEmpty that tests if a regular expression matches the empty string, and am using it now in both Match and FMatch
