### ISSUE TITLE
Loops and infinity

### ISSUE THREAD

**Issue by ksqsf** [boazbk/tcs#572]
**Chapter name**: Loops and infinity

**List of bugs/typos**

1. Figure "Overview of our models for finite and unbounded computation." Chapter numbers are incorrect.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/23358293/89245350-37743a80-d63b-11ea-9f59-e035d5cb314a.png">

2. A link to "the appendix" below "XOR in NAND-TM", https://tiny.cc/introtcsappendix, is invalid.

**Comment by boazbk** [comment]
Dropped that link - will fix chapter numbers later
