### ISSUE TITLE
Definition of HALT

### ISSUE THREAD

**Issue by ksqsf** [boazbk/tcs#580]
In theorem "Uncomputability of Halting function", HALT is defined as

> Let HALT ∶ {0, 1}∗ → {0, 1} be the function such that for every string 𝑀 ∈ {0, 1}∗, HALT(𝑀 , 𝑥) = 1 if Turing machine 𝑀 halts on the input 𝑥 and HALT(𝑀 , 𝑥) = 0 otherwise.

This is a little weird as HALT takes only one input. Maybe you want to change it to something like

> HALT ∶ {0, 1}∗ → {0, 1}∗ → {0, 1}

and give a lemma about the computability of two-input functions.

**Comment by boazbk** [comment]
This is something that we do consistently and remark on it at the beginning - we can always encode a pair of strings as a single string, and so refer to two-input functions as mapping strings to strings.

(Similarly in NP completeness, even though the independent set problem takes as input a graph G and a number k, we think of it as mapping a string to a bit)
