### ISSUE TITLE
Modeling running time: Suggestion for more context for P/poly

### ISSUE THREAD

**Issue by marwahaha** [boazbk/tcs#584]
I think it would be nice to include more information about P/poly as a single Turing machine with an advice function. 
I see it mentioned in the solved exercise and bibliographic notes, but I wish I had more information on whether it is a common way to conceptualize P/poly (vs PSIZE in the chapter).

**Comment by boazbk** [comment]
I think it's actually not a very common way to think of P/poly - typically people do think in terms of circuits, so maybe bibliographic notes is the place for it.
