### ISSUE TITLE
P = NP chapter; sensitivity suggestions

### ISSUE THREAD

**Issue by marwahaha** [boazbk/tcs#586]
This chapter includes a couple comments that are not exactly related to the text and may make some people uncomfortable. I suggest changing these lines without altering the main message of the text.

> She does not “pussyfoot around” or take “half measures”.
* pussyfoot is occasionally sexual slang ([here](https://www.urbandictionary.com/define.php?term=pussyfoot#12970241)) or related to sexually-inspired slang ([here](https://www.urbandictionary.com/define.php?term=penisfoot))
* I suggest changing "pussyfoot around" with a [synonym](https://www.thesaurus.com/browse/pussyfoot).

> In fact, creativity already is to a large extent automated or minimized (e.g., just see how much popular media content is mass-produced), and as in most professions we should expect to see the need for humans diminish with time even if P≠NP
* I disagree with this statement.
  *  I'm not confident creativity is "minimized" because popular media is mass-produced; I think more people have additional ways to do creative things (even if they are not popular). See for example Etsy, memes, Twitter.
  * I don't know if "most" professions will require fewer humans; I expect different professions and industries to develop as humans continue to exist. The root of my disagreement concerns the phrase "need for humans"; need for humans to do what?
* I suggest removing the sentence.

Of course, this is up to you.

**Comment by boazbk** [comment]
1) Thanks! I didn't realize the sexual connotation - replaced  this with "beat around the bush"

2) You are right that the sentence gets into a discussion that's not so relevant for this book - I removed it.
