### ISSUE TITLE
Bug in Math Review

### ISSUE THREAD

**Issue by madhu-harvard** [boazbk/tcs#608]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Mathematical Background**: The names of the chapter and section(s) where the typos/bugs/are. (Please use _names_, not _numbers_, since the numbers tend to change).

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. Basic Discrete Math Objects -> Functions -> Basic facts about functions: Fourth bullet, (a) implies (c) asserts that: If |S| <= |T| then there is an onto function from T to S. But this needs S to be non-empty!

**Comment by boazbk** [comment]
You are right! Will fix shortly
