### ISSUE TITLE
Small typo, p. 99

### ISSUE THREAD

**Issue by Seventeen-29** [boazbk/tcs#617]
On p.99, in the 2nd paragraph from bottom, it currently reads F(10) = F(2), F(11) = F(3), but it should read F(10) = f(2), F(11) = f(3), with lowercase f's.

**Comment by marwahaha** [comment]
This is fixed by https://github.com/boazbk/tcs/commit/5427362f64fb4c9faecef6262eb2e8d23c6054f1
