### ISSUE TITLE
chapter 16: NP in terms of proof systems

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#62]
it would be nice to explain the connection between the definition of NP and the definition of proof systems in Chapter 12, and explain that polynomial-time verifiability holds for all natural examples of mathematical proof systems and thus really what NP is asking for is SHORT proofs - and indeed the SHORT PROOF problem is NP-complete for most mathematical proof systems.  one can mention Godel's letter to von Neumann at this point too.

**Comment by boazbk** [comment]
Thanks - added that.
