### ISSUE TITLE
double 'in' in What if P equals NP?

### ISSUE THREAD

**Issue by nsheely** [boazbk/tcs#625]
Chapter: What if P equals NP?

Section: Optimization 

In the line

f $\mathbf{P}=\mathbf{NP}$ then for every for every string $x\in {0,1}^$ and number $k$, we can test in in $poly(|x|,m)$ time whether there exists $y$ such that $f(x,y) \geq k$, or in other words test whether $\max_{y \in {0,1}^m} f(x,y) \geq k$.

repeats the word 'in' twice in a row.

May have intended it to be 'it in'?

Nathan Sheely

**Comment by hywn** [comment]
I think removing the extra 'in' altogether makes the most sense; suggested in #626
