### ISSUE TITLE
chapter 16: nondeterminism

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#63]
I'd advocate adding a few more (informal) words about the concept of "nondeterminism" in the main body (not just the bibliography) as it does play an important role elsewhere in CS.  Many algorithms operate not deterministically but are also affected by other factors or inputs coming from their environment that the programmer may not have control over.  Asking whether it is *possible* for such an algorithm to have a particular behavior (e.g. have some security failure) on some computation path (e.g. when an adversary controls some of the external inputs) is an example of a nondeterministic computation of the kind captured by the class NP.

**Comment by boazbk** [comment]
Good comment but am not sure if it's not confusing. Possibly this can be worked on as a concrete example of an NP problem of whether there is a sequence of user inputs that leads to a troublesome state.
This seems like also a comment that could be worked into the "restricted computational models" chapter, as this is one of the motivations for them.
