### ISSUE TITLE
Figure 6.2, python program

### ISSUE THREAD

**Issue by benjaminb** [boazbk/tcs#630]
Hi there, taking CS121 right now. The python program in figure 6.2 computes the sum of 1's in a list, but I think you intended for this XOR to compute the parity one 1's

**Comment by nsheely** [comment]
I think you are correct.

Following the directions in [https://github.com/boazbk/tcs/blob/master/CONTRIBUTING.md](https://github.com/boazbk/tcs/blob/master/CONTRIBUTING.md)
If you want to be added the the acknowledgements, you should include your name in your issue

**Comment by boazbk** [comment]
Thanks to you both!!

**Comment by benjaminb** [comment]
> Thanks to you both!!

Thanks guys! My name is Benjamin Basseri btw
