### ISSUE TITLE
In dark mode, some text sections have bad contrast, rendering text unreadable

### ISSUE THREAD

**Issue by dhruvsharma78** [boazbk/tcs#633]
Some text blocks have a blue or green background. When the foreground color is black, this works fine. But in dark mode, the foreground color is white, even on the colored blocks. This renders text unreadable

An example from section 1.4.3:
[
<img width="884" alt="Screen Shot 2020-10-28 at 17 38 33" src="https://user-images.githubusercontent.com/29253788/97443497-87198800-1944-11eb-89c4-dce94bc9e41c.png">
](url)

**Comment by boazbk** [comment]
Thanks! I wonder if there is some CSS magic that can automatically change to other colors - if you have suggestions let me know

**Comment by boazbk** [comment]
Closing it since I am not an expert in HTML to fix this
