### ISSUE TITLE
chapter 16: Ladner's theorem

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#64]
"However, it is believed that there exist problems in NP that are neither in P not in
NP, and in fact a result known as “Ladner’s Theorem” shows that if
P 6= NP then this is the case (see also Exercise 16.1)."

replace "not in NP" with "nor NP-complete".   

Before or when mentioning Ladner's theorem, it seems good to draw two venn diagrams describing the possible states of the world.  One where P=NP=NP-complete (good exercise to have them show that if P=NP then also all of P other than the constant functions is NP-complete) and one where NP has P and the NP-complete problems as two disjoint subsets.  

Also, it is worth mentioning somewhere that there are natural candidates for NP-intermediate problems, like Factoring, Nash Equilibria, anything in NP intersect co-NP, all crypto assumptions (forward pointer to crypto chapter)

**Comment by boazbk** [comment]
Added - thanks!
