### ISSUE TITLE
TM Return Convention

### ISSUE THREAD

**Issue by ToddMorrill** [boazbk/tcs#640]
The following TM return convention used in chapter *Universality and uncomputability* differs from the convention defined in chapter *Loops and infinity*. The example below returns everything on the tape between the start position and the first phi on the tape. The TM definition from chapter *Loops and infinity* returns everything on the tape between the start position and the read head position.

It might be worth adding a note to the reader in chapter *Universality and uncomputability* that this convention differs from that defined in chapter *Loops and infinity* but that they are both equally powerful and that it is useful to gain exposure to both conventions. This was a source of considerable confusion on one of the problem sets in the most recent installment of CS121. 
 
```python
# constants
def EVAL(δ,x):
    '''Evaluate TM given by transition table δ
    on input x'''
    Tape = ["▷"] + [a for a in x]
    i = 0; s = 0 # i = head pos, s = state
    while True:
        s, Tape[i], d = δ[(s,Tape[i])]
        if d == "H": break
        if d == "L": i = max(i-1,0)
        if d == "R": i += 1
        if i>= len(Tape): Tape.append('Φ')

    j = 1; Y = [] # produce output
    while Tape[j] != 'Φ':
        Y.append(Tape[j])
        j += 1
    return Y
```

**Comment by boazbk** [comment]
Thanks! I'll change the convention to be consistent - until the first empty place in both.
