### ISSUE TITLE
chapter 18: implications of P=NP

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#65]
Rather than jumping to the very abstract "quantifier elimination" and PH, the chapter could discuss how optimization becomes easy (e.g. pointing to an exercise like the one I suggested - finding the largest clique or longest TSP tour), machine learning becomes easy, finding mathematical proofs becomes easy, crypto collapses.  if PH is going to be discussed, at least some natural examples of problems it captures (other than those in NP) would help make it more concrete!  otherwise it just seems like generalization for the sake of generalization.

**Comment by boazbk** [comment]
Thanks, added now
