### ISSUE TITLE
Computation and Representation: Finite Representations Typo

### ISSUE THREAD

**Issue by ProgramCounterr** [boazbk/tcs#668]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter name**: Computation and Representation: Finite Representations

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. Typo: emptry
"**Lemma 2.16**  
For every two non-emptry finite sets **S**, **T**, there exists a one-to-one **E**: **S** → **T** if and only if **∣S∣** ≤ **∣T∣**."

**Comment by boazbk** [comment]
Fixed by now - thanks!
