### ISSUE TITLE
Exercise 3.13 needs revision

### ISSUE THREAD

**Issue by GerryFudd** [boazbk/tcs#696]
**Chapter 3, Defining Computation**

1. Exercise 3.13 contains a definition for a NAND approximator: a function from R^2 to R such that the squares [-1/3,1/3]x[-1/3,1/3], [-1/3,1/3]x[2/3,4/3], and [2/3.4/3]x[-1/3,1/3] map to the interval [2/3,4/3] and the square [2/3,4/3]x[2/3,4/3] maps to [-1/3,1/3].  You then ask the student to show that a NAND approximator may be constructed from an affine function from R^2 to R, either the ReLU function or the sigmoid function, and an affine function from R to R. There are a couple of issues with this. 
  a.  It's impossible to construct an affine function that is simultaneously greater than 2/3 at (1/3,4/3), (4/3,1/3), and (1/3,1/3) and also less than 1/3 at (2/3,2/3). To see why, note that the point (2/3,2/3) falls inside of the triangle formed by the other three points. To remedy this, I suggest that you use a number smaller than 1/4 in your definition of a NAND approximator (eg 1/5 would be sufficiently small). This change is sufficient to construct a NAND approximator using an affine function, the sigmoid function, and an affine function.
  b. Even if you choose an arbitrarily small value 1/4>q>0 to define a NAND approximator as a function where |f(a,b)-NAND([a],[b])|<q whenever min(|a|,|1-a|)<q and min(|b|,|1-b|)<q it's not possible to construct a NAND approximator by sandwiching the ReLU function between two affine functions. An affine function that is greater than 1-q at (q,1+q) and (1+q,q) but less than q at (1-q,1-q) must have a gradient of at least 2/sqrt(2). The gradient must be even steeper if isn't oriented along the diagonal (a=b). Given such an arrangement, the ReLU function only allows you to bound this affine function on one side. Assuming that you bound this function above, the affine function can't fall below -q by the time it reaches the point (a,b)=(1+q,1+q). This is impossible because the affine function may be at most q at f(1-q,1-q) and this means that the gradient of the affine function can't be greater than 1/sqrt(2).
    Whatever activation function is sandwiched between the affine functions needs to behave more like the sigmoid function in that it needs to be bounded above and below in order to keep the NAND approximator from overflowing the max or min allowed values too quickly. You could use some other piecewise linear activation function that is defined as g(x)=min(max(0,x),1) for this purpose and the exercise would be possible.

**Comment by boazbk** [comment]
Thanks! Does this fix it?

Show that there is a NAND approximator $f$ defined as $f(a,b) = L(DReLU(L'(a,b)))$ where $L':\mathbb{R}^2 \rightarrow \mathbb{R}$ is an _affine_ function (of the form $L'(a,b)=\alpha a + \beta b + \gamma$ for some $\alpha,\beta,\gamma \in \mathbb{R}$), $L$ is an affine function (of the form $L(y) = \alpha y + \beta$ for $\alpha,\beta \in \mathbb{R}$), and $DReLU:\mathbb{R} \rightarrow \mathbb{R}$, is the function defined as $DReLU(x) = \min(1,\max(0,x))$. Note that $DReLU(x) = 1-ReLU(1-ReLU(x))$  where $ReLU(x)=\max(x,0)$ is the rectified linear unit activation function.

Can you add yourself to the acknowledgement?
