### ISSUE TITLE
Randomized computation

### ISSUE THREAD

**Issue by jingyig99** [boazbk/tcs#704]
**Chapter name**: Randomized computation.

**List of bugs/typos**

1. In the subsection "Randomized Reduction", the definition of B reduces to C under a randomized polynomial time reduction is a bit confusing. Comparing to Karp reduction, when we reduce A to B we transfer the instances in A into instances in B, so under a similar logic in this case we should transfer instances in B into instances in C. Therefore I think instead of writing "Pr[B(M(x)) = C(x)] >= 2/3," "Pr[B(x) = C(M(x))] >= 2/3" makes more sense.

2. Still regarding the same definition as in 1, the role of the probabilistic TM M made me feel a little confused since in the same chapter, probabilistic Turing machine are defined to be only able to output 0 or 1, whereas in this case I'm assuming the authors intended to design M to be able to take in an instance in B and output a valid instance in C with high probability. I'm not sure whether I have the correct understanding or not since I searched online but cannot find other authorized resources, but it would be great if some explanation of this could be added. 

3. In the definition of RTIME(T(n)), the second line should be $x \notin L \implies Pr(M(x) = 1) = 0.$

Thanks a lot!

**Comment by boazbk** [comment]
I am not finding these - maybe I modified the text and they don't exist anymore?
