### ISSUE TITLE
Chapter 6: Functions with Infinite Domains, Automata, and Regular Expressions Word Missing

### ISSUE THREAD

**Issue by paritashahh** [boazbk/tcs#727]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

Chapter 6: Functions with Infinite Domains, Automata, and Regular Expressions 

Proof of Pumping Lemme first line should be "The idea behind the proof is the following" instead of "The idea behind the proof the following"

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

1. bug 1

2. bug 2

**Comment by boazbk** [comment]
Thanks! I think it was already fixed
