### ISSUE TITLE
Chapter 16: What if P equals NP?

### ISSUE THREAD

**Issue by jimmyqtran** [boazbk/tcs#729]
**Chapter name**: What if P equals NP?

**List of bugs/typos**

1. In the pink box sectioned, ***This chapter: a non mathy overview***: There should be a hyphen between "non" and "mathy" since non mathy is used as an adjective to describe overview. 

2. In the pink box sectioned, ***This chapter: a non mathy overview***: "This chapter shows some of the truly breathtaking _concsequences_..." should read as "This chapter shows some of the truly breathtaking _consequences_..."

**Comment by boazbk** [comment]
Fixed - thanks!
