### ISSUE TITLE
typo in ch. 13 modeling running time - "non mathy overview"

### ISSUE THREAD

**Issue by olivia-fu** [boazbk/tcs#754]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

**Chapter 13, Modeling Running Time**: The names of the chapter and section(s) where the typos/bugs/are. (Please use _names_, not _numbers_, since the numbers tend to change).

**List of bugs/typos**

Please don't refer to page numbers or even section numbers since they tend to change - section titles are best. Also, please give some context (sentence before/after the issue) to make it easier for me to find it - thanks!

- In the second sentence of the "non mathy overview" at the start of the chapter, we have: "As discussed in Chapter 12, running time is not a number, rather what we care about is the scaling behevaiour of the number of steps as the input size grows." Typo on behavior.

**Comment by LoftyDroid** [comment]
Can you please assign this to me? I would like to contribute to this project.
