### ISSUE TITLE
[Chapter 16: What if P equals NP?] Disappearing sidenote in PDF

### ISSUE THREAD

**Issue by junemoretz** [boazbk/tcs#759]
**Chapter name**: What if P equals NP?

**List of bugs/typos**

The fifth sidenote (in section 16.4 Quantifier Elimination, a reference to the existence of which appears after the text "which has the form (16.1).") does not appear in the PDF. Sidenotes 4 and 6 appear properly.

**Comment by boazbk** [comment]
This is a latex bug which I am not 100% sure how to solve but tried to make some sidenotes into parenthetical remarks which I hope will help
