### ISSUE TITLE
Chapter 16 Theorem Number

### ISSUE THREAD

**Issue by paritashahh** [boazbk/tcs#767]
Please open a different issue for each chapter, with the **chapter name** in the title - thank you!

Please edit the fields below

Chapter 16 (What if P = NP?) section 16.2 (Optimization) 

1. Theorem about Optimization is labeled 16.3 but there is no theorem 16.2 (the previous theorem about FIND is theorem 16.1)

**Comment by boazbk** [comment]
Algorithms and Theorems share counters which I think is fine?
