### ISSUE TITLE
Chapter 18 - Probability Theory 101

### ISSUE THREAD

**Issue by Adirlou** [boazbk/tcs#770]
Probability Theory 101

* The issue is about a **figure** in the section called *Random Coins*, when considering binary strings with sum (modulo 2) equal to 0. The corresponding figure, which shows the binary tree and highlights binary strings with sum (modulo 2) equal to 0 (in the green boxes) is not fully correct. It is currently highlighting the strings 000, 010, 100, 110, but the correct ones should be 000, 011, 101, 110.

<img width="460" alt="Screenshot 2022-11-11 at 14 33 32" src="https://user-images.githubusercontent.com/6523110/201279531-a5345f0f-5d53-49c7-b6c9-cda24bdd2d2f.png">

**Comment by boazbk** [comment]
Thanks - should be fixed shortly!
