### ISSUE TITLE
Figure 16.2

### ISSUE THREAD

**Issue by jacobmeyerson** [boazbk/tcs#78]
I think the way in which Figure 16.2 indexes variables is inconsistent with the description of the indexing in the proof (pg. 341).  

The description on pg. 341 says that "if one or both of bar and blah is an input variable x_i then we use z_i in the constraint."  But in Figure 16.2, z_0 = NAND(z_{m+2},z_{m+3}) corresponds with the line a_1 = x_2 NAND x_3.

**Comment by boazbk** [comment]
Thanks - added a comment there for now and will update the figure next chance I get

**Comment by boazbk** [comment]
I have now rewritten things and I believe the figure is no longer inconsistent - thanks!
