### ISSUE TITLE
Figure 19.4

### ISSUE THREAD

**Issue by jacobmeyerson** [boazbk/tcs#79]
Figure 19.4:
---Blue is highlighted where x_1 = 1, where Event B is x_1 = 0; I think this is a mistake.
---"C is negatively correlated with A and positively correlated with B"; I think negative should be switched to positive, and positive switched to negative.
---"The three events A,B,E are not mutually independent since their intersection has probability 2/8 = 1/4"; if Event B is x_1 = 0 (not x_1 = 1, as is colored), then this doesn't make sense, as A,B,E have an empty intersection.

**Comment by boazbk** [comment]
correct on all counts - thanks!
