### ISSUE TITLE
CH 4.3.1, Proof of Lemma 4.11

### ISSUE THREAD

**Issue by kascrizzi** [boazbk/tcs#791]
The last sentence of the proof is: "Thus we can compute _LOOKUP<sub>k</sub>(x,i)_ by first computing _a_ and _b_ and then outputting _IF(**i<sub>k-1</sub>**,a,b)_."

To match Lemma 4.11, shouldn't the output be _IF(**i<sub>0</sub>**,a,b)_?

**Comment by boazbk** [comment]
Yes! In fact, I think it is $IF(i_0,b,a)$ since if the most significant bit is zero then we output $a$ and otherwise we output $b$.
