### ISSUE TITLE
Theorem 20.3 proof

### ISSUE THREAD

**Issue by jacobmeyerson** [boazbk/tcs#80]
"(1/3)^(n/2) = sqrt(3)^(-n/2)" --- I think this should sqrt(3)^(-n), since sqrt(3) = 3^(1/2)

"Repeat this 100 (sqrt (3))^(n/2) times" --- I think this should be 100 (sqrt 3)^n times.

Furthermore, to be consistent throughout the proof, I think that T should be 100 (sqrt 3)^n.

**Comment by boazbk** [comment]
You are right - thanks!
