### ISSUE TITLE
chapter 21

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#87]
Before getting into BPP vs. P, you could discuss some other, more basic complexity-theoretic aspects of randomized computation and BPP, which relate more to the material earlier in the course:
   * randomized algorithms are considered a realistic and physically implementable model of computation.  thus actually NP vs. BPP is a more relevant question about the tractability of the NP-complete problems than NP vs. P.  (Of course they become the same question if BPP=P, but (a) we don't have a proof of the latter, and (b) randomized algorithms are also the more relevant model in other settings where randomized algorithms are provably stronger than deterministic ones, such as distributed protocols and sublinear time.)   
   * we don't even know how to rule out BPP=NEXP!
   * our theory of NP-completeness is still relevant to NP vs. BPP.  If any NP-complete problem is in BPP, then NP\subseteq BPP.
   * search vs. decision also holds for randomized algorithms:  If NP\subseteq BPP, then we can find witnesses in randomized polynomial time (and hence actually we can get one-sided error, NP=RP).

**Comment by boazbk** [comment]
added - thanks!
