### ISSUE TITLE
Constants in Proof of Theorem 18.8

### ISSUE THREAD

**Issue by jacobmeyerson** [boazbk/tcs#89]
I think the constants used in the Theorem 18.8 proof are off: I think it should be that "X ix very likely to be at most 1000n" (rather than 100n), and that sqrt(n) should be less than 0.001 n (rather than 0.01n), for we are looking at the interval [0.499n, 0.501n], which is 0.001 n off of the expected value of 0.5.

**Comment by boazbk** [comment]
I think you mean the discussion after the proof and not the proof itself.

You're right about the second comment but not the first. It is true that X is very likely (i.e. 99% probability) to be at most 100n by Markov.
