### ISSUE TITLE
chapter 21 (crypto)

### ISSUE THREAD

**Issue by SalilVadhan** [boazbk/tcs#95]
It would be nice to spend much more time relating this chapter to what was done earlier in the course, rather than delving into more crypto-specific conceptual ideas (such as relating indistinguishability to semantic security like notions, which I'd advocate dropping entirely).  

For example:
1) emphasizing that what was needed for crypto to turn from an art to a science is the development of the framework of computational complexity (though one can note that Shannon hinted at using boolean circuit size), and the concept of reductions
2) if P=NP or even NP\subseteq BPP, all of crypto can be broken efficiently.  some of this was already hinted in the "what if P=NP" chapter, but it is worth working out some of it in more detail here, now that you have precise definitions for crypto.  
3) We'd love to base crypto on the assumption that NP not in BPP (e.g. design a cryptosystem s.t. any successful attacker can be converted into an algorithm that solves 3-SAT), but this assumption seems too weak (need average-case hardness, and even to generate hard instances together with solutions).  Still the concept of reductions plays a key role.  We know many concrete assumptions (e.g. factoring random products of two primes) where we can design cryptosystems s.t. breaking the assumption can be reduced to breaking the cryptosystem.

**Comment by boazbk** [comment]
Thanks! I think now more is added, and will try to do more in the next pass
